const fortunes = [
    "It's better to be quotable than to be honest. 		-- Tom Stoppard ",
    "Love is sentimental measles. ",
    "Your compliance with all terms and conditions, expressed and implied, is automatic upon viewing. ",
    "Federal law prohibits dispensing without a prescription. ",
    "My notion of a husband at forty is that a woman should be able to change him, like a bank note, for two twenties. ",
    "To be trusted is a greater compliment than to be loved. ",
    "Do not drink coffee in early A.M.  It will keep you awake until noon. ",
    "FLASH! Intelligence of mankind decreasing. Details at ... uh, when the little hand is on the .... ",
    "Pardo's First Postulate: 	Anything good in life is either illegal, immoral, or fattening.  Arnold's Addendum: 	Everything else causes cancer in rats. ",
    "There can be no twisted thought without a twisted molecule. 		-- R. W. Gerard ",
    "Of course a platonic relationship is possible -- but only between husband and wife. ",
    "Give your very best today.  Heaven knows it's little enough. ",
    "In computing, the mean time to failure keeps getting shorter. ",
    "Marriage is learning about women the hard way. ",
    "At participating locations only. ",
    "Pickle's Law: 	If Congress must do a painful thing, 	the thing must be done in an odd-number year. ",
    "Perl has a long tradition of working around compilers. 		-- Larry Wall in <199708252256.PAA00105@wall.org> ",
    "It got to the point where I had to get a haircut or both feet firmly planted in the air. ",
    "If you lose a son you can always get another, but there's only one Maltese Falcon. 		-- Sidney Greenstreet, \"The Maltese Falcon\" ",
    "Drinking coffee for instant relaxation?  That's like drinking alcohol for instant motor skills. 		-- Marc Price ",
    "You will become rich and famous unless you don't. ",
    "Here I am at the flea market but nobody is buying my urine sample bottles ... ",
    "To have died once is enough. 		-- Publius Vergilius Maro (Virgil) ",
    "Lizzie Borden took an axe, And plunged it deep into the VAX; Don't you envy people who Do all the things YOU want to do? ",
    "...his disciples lead him in; he just does the rest. 		-- The Who, \"Tommy\" ",
    "Tempt me with a spoon! ",
    "Let's remind ourselves that last year's fresh idea is today's cliche. 		-- Austen Briggs ",
    "You can create your own opportunities this week.  Blackmail a senior executive. ",
    "Has anyone ever tasted an \"end\"?  Are they really bitter? ",
    "It has long been an axiom of mine that the little things are infinitely the most important. 		-- Sir Arthur Conan Doyle, \"A Case of Identity\" ",
    "Spectacularism: 	A fascination with extreme situations. 		-- Douglas Coupland, \"Generation X: Tales for an Accelerated 		   Culture\" ",
    "If I traveled to the end of the rainbow As Dame Fortune did intend, Murphy would be there to tell me The pot's at the other end. 		-- Bert Whitney ",
    "The real trouble with reality is that there's no background music. ",
    "You can move the world with an idea, but you have to think of it first. ",
    "Atlanta: 	An entire city surrounded by an airport. ",
    "When a man knows he is to be hanged in a fortnight, it concentrates his mind wonderfully. 		-- Samuel Johnson ",
    "Seeing that death, a necessary end, Will come when it will come. 		-- William Shakespeare, \"Julius Caesar\" ",
    "If you can't get your work done in the first 24 hours, work nights. ",
    "If your happiness depends on what somebody else does, I guess you do have a problem. 		-- Richard Bach, \"Illusions\" ",
    "\"I will make no bargains with terrorist hardware.\" 		-- Peter da Silva ",
    "Patience is a minor form of despair, disguised as virtue. 		-- Ambrose Bierce, on qualifiers ",
    "A beer delayed is a beer denied. ",
    "Abstainer, n.: 	A weak person who yields to the temptation of denying himself a 	pleasure. 		-- Ambrose Bierce, \"The Devil's Dictionary\" ",
    "Your mind understands what you have been taught; your heart, what is true. ",
    "Hey, what do you expect from a culture that *drives* on *parkways* and *parks* on *driveways*? 		-- Gallagher ",
    "Are you perchance running on a 64-bit machine? 		-- Larry Wall in <199711102149.NAA16878@wall.org> ",
    "Alimony is the curse of the writing classes. 		-- Norman Mailer ",
    "I give you the man who -- the man who -- uh, I forgets the man who? 		-- Beauregard Bugleboy ",
    "Never sleep with a woman whose troubles are worse than your own. 		-- Nelson Algren ",
    "Savage's Law of Expediency: 	You want it bad, you'll get it bad. ",
    "Q:	What do you call a principal female opera singer whose high C 	is lower than those of other principal female opera singers? A:	A deep C diva. ",
    "QOTD: 	\"Just how much can I get away with and still go to heaven?\" ",
    "\"In my opinion, Richard Stallman wouldn't recognise terrorism if it came up and bit him on his Internet.\" 		-- Ross M. Greenberg ",
    "How wonderful opera would be if there were no singers. ",
    "Mencken and Nathan's Ninth Law of The Average American: 	The quality of a champagne is judged by the amount of noise the 	cork makes when it is popped. ",
    "Double! ",
    "\"Even nowadays a man can't step up and kill a woman without feeling just a bit unchivalrous ...\" 		-- Robert Benchley ",
    "Yield to Temptation ... it may not pass your way again. 		-- Lazarus Long, \"Time Enough for Love\" ",
    "It is not enough to have great qualities, we should also have the management of them. 		-- La Rochefoucauld ",
    "Freshest if eaten before date on carton. ",
    "NOTICE: 	Anyone seen smoking will be assumed to be on fire and will 	be summarily put out. ",
    "Ferengi Rule of Acquisition #22: A wise man can hear profit in the wind. -- Rules of Acquisition (DS9 episode), False Profits (VOY episode) ",
    "Slowly and surely the unix crept up on the Nintendo user ... ",
    "Shift to the left, Shift to the right, Mask in, mask out, BYTE, BYTE, BYTE !!! ",
    "Spouse, n.: 	Someone who'll stand by you through all the trouble you 	wouldn't have had if you'd stayed single. ",
    "\"I found out why my car was humming.  It had forgotten the words.\" ",
    "Only two groups of people fall for flattery -- men and women. ",
    "*** Knghtbrd is now known as SirKewLDooD *** Mercury kicked SirKewlDooD from #quakeforge (*WHACK*) ",
    "I've found my niche.  If you're wondering why I'm not there, there was this little hole in the bottom ... 		-- John Croll ",
    "Everybody gets free BORSCHT! ",
    "A man who turns green has eschewed protein. ",
    "Tell the truth or trump--but get the trick. 		-- Mark Twain, \"Pudd'nhead Wilson's Calendar\" ",
    "I can't decide whether to commit suicide or go bowling. 		-- Florence Henderson ",
    "\"Is it really you, Fuzz, or is it Memorex, or is it radiation sickness?\" 		-- Sonic Disruptors comics ",
    "People will buy anything that's one to a customer. ",
    "Q:	What do they call the alphabet in Arkansas? A:	The impossible dream. ",
    "It's bad enough that life is a rat-race, but why do the rats always have to win? ",
    "Replace with same type. ",
    "Your business will go through a period of considerable expansion. ",
    "Cursor, n.: 	One whose program will not run. 		-- Robb Russon ",
    "I was at this restaurant.  The sign said \"Breakfast Anytime.\"  So I ordered French Toast in the Rennaissance. 		-- Steven Wright ",
    "Ferengi Rule of Acquisition #68: Risk doesn't always equal reward. -- Star Trek Online (video game) ",
    "For off-road use only. ",
    "Common sense is instinct, and enough of it is genius. 		-- Josh Billings ",
    "Filmed before a live audience. ",
    "Bradley's Bromide: 	If computers get too powerful, we can organize 	them into a committee -- that will do them in. ",
    "C:\> WIN Bad command or filename  C:\> LOSE Loading Microsoft Windows ... ",
    "Davis's Dictum: 	Problems that go away by themselves, come back by themselves. ",
    "The discerning person is always at a disadvantage. ",
    "All the really good ideas I ever had came to me while I was milking a cow. 		-- Grant Wood ",
    "These days the necessities of life cost you about three times what they used to, and half the time they aren't even fit to drink. ",
    "May cause drowsiness. ",
    "broad-mindedness, n: 	The result of flattening high-mindedness out. ",
    "Given sufficient time, what you put off doing today will get done by itself. ",
    "The woman you buy -- and she is the least expensive -- takes a great deal of money.  The woman who gives herself takes all your time. 		-- Balzac ",
    "Some people have parts that are so private they themselves have no knowledge of them. ",
    "Our similarities are different. -Dale Berra, son of Yogi ",
    "Ma Bell is a mean mother! ",
    "It is easier to get forgiveness than permission. ",
    "\"The Computer made me do it.\" ",
    "Somewhere, just out of sight, the unicorns are gathering. ",
    "It's later than you think, the joint Russian-American space mission has already begun. ",
    "It is not a good omen when goldfish commit suicide. ",
    "I profoundly believe it takes a lot of practice to become a moral slob. 		-- William F. Buckley ",
    "Be cheerful while you are alive. 		-- Phathotep, 24th Century B.C. ",
    "* Knghtktty is not going to ask how zucchini got into the discussion ... ",
    "<Kensey> RMS for President??? <RelDrgn> ...or ESR, he wants a new job ;) ",
    "After all, all he did was string together a lot of old, well-known quotations. 		-- H. L. Mencken, on Shakespeare ",
    "QOTD: 	\"Oh, no, no...  I'm not beautiful.  Just very, very pretty.\" ",
    "\"Professional certification for car people may sound like an oxymoron.\" -The Wall Street Journal, page B1, Tuesday, July 17, 1990. ",
    "Let us remember that ours is a nation of lawyers and order. ",
    "You worry too much about your job.  Stop it.  You are not paid enough to worry. ",
    "Make no little plans; they have no magic to stir men's blood. 		-- Daniel Hudson Burnham ",
    "Commoner's three laws of ecology: 	(1) No action is without side-effects. 	(2) Nothing ever goes away. 	(3) There is no free lunch. ",
    "... the heat come 'round and busted me for smiling on a cloudy day. ",
    "Killing turkeys causes winter. ",
    "In the next world, you're on your own. ",
    "Death is only a state of mind.  Only it doesn't leave you much time to think about anything else. ",
    "Avoid gunfire in the bathroom tonight. ",
    "C is quirky, flawed, and an enormous success 	-- Dennis M. Ritchie ",
    "A shapely CATHOLIC SCHOOLGIRL is FIDGETING inside my costume.. ",
    "As you will see, I told them, in no uncertain terms, to see Figure one. 		-- Dave \"First Strike\" Pare ",
    "When you're in command, command. 		-- Admiral Nimitz ",
    "* TwingyAFK is shopping for 17\" flat panel * aav sells TwingyAFK a piece of plywood ",
    "Sorry, no fortune this time. ",
    "In 1869 the waffle iron was invented for people who had wrinkled waffles. ",
    "May explode if improperly recharged. ",
    "Nothing is easier than to denounce the evildoer; nothing is more difficult than to understand him. 		-- Fyodor Dostoevski ",
    "Pascal Users: 	To show respect for the 313th anniversary (tomorrow) of the 	death of Blaise Pascal, your programs will be run at half speed. ",
    "Health is merely the slowest possible rate at which one can die. ",
    "You will hear good news from one you thought unfriendly to you. ",
    "Where it is a duty to worship the sun it is pretty sure to be a crime to examine the laws of heat. 		-- Christopher Morley ",
    "Nice guys finish last, but we get to sleep in. 		-- Evan Davis ",
    "\"Summit meetings tend to be like panda matings.	 The expectations are always high, and the results usually disappointing.\" 		-- Robert Orben ",
    "If you lose a son you can always get another, but there's only one Maltese Falcon. 		-- Sidney Greenstreet, \"The Maltese Falcon\" ",
    "Q:	What do you get when you cross a mobster with an international standard? A:	You get someone who makes you an offer that you can't understand! ",
    "Come, muse, let us sing of rats! 		-- From a poem by James Grainger, 1721-1767 ",
    "A sect or party is an elegant incognito devised to save a man from the vexation of thinking. 		-- Ralph Waldo Emerson, Journals, 1831 ",
    "There is hopeful symbolism in the fact that flags do not wave in a vacuum. 		-- Arthur C. Clarke ",
    "A quarrel is quickly settled when deserted by one party; there is no battle unless there be two.  -- Seneca ",
    "Don't put off for tomorrow what you can do today because if you enjoy it today, you can do it again tomorrow. ",
    "It got to the point where I had to get a haircut or both feet firmly planted in the air. ",
    "Kliban's First Law of Dining: 	Never eat anything bigger than your head. ",
    "If you just try long enough and hard enough, you can always manage to boot yourself in the posterior. 		-- A. J. Liebling, \"The Press\" ",
    "I couldn't possibly fail to disagree with you less. ",
    "My little brother got this fortune: 	nohup rm -fr /& So he did... ",
    "System checkpoint complete. ",
    "If God hadn't wanted you to be paranoid, He wouldn't have given you such a vivid imagination. ",
    "Universe, n.: 	The problem. ",
    "Beggar to well-dressed businessman: 	\"Could you spare $20.95 for a fifth of Chivas?\" ",
    "The reward of a thing well done is to have done it. 		-- Emerson ",
    "It is a profitable thing, if one is wise, to seem foolish. 		-- Aeschylus ",
    "The English country gentleman galloping after a fox -- the unspeakable in full pursuit of the uneatable. 		-- Oscar Wilde, \"A Woman of No Importance\" ",
    "There is no act of treachery or mean-ness of which a political party is not capable; for in politics there is no honour. 		-- Benjamin Disraeli, \"Vivian Grey\" ",
    "Somebody set up us the bomb.     -- Cut scene from the game \"Zero Wing\"     -- https://en.wikipedia.org/wiki/All_your_base_are_belong_to_us ",
    "QOTD: 	\"What I like most about myself is that I'm so understanding 	when I mess things up.\" ",
    "Beauty, brains, availability, personality; pick any two. ",
    "When in doubt, lead trump. ",
    "In Blythe, California, a city ordinance declares that a person must own at least two cows before he can wear cowboy boots in public. ",
    "Ferengi Rule of Acquisition #97: Enough is never enough. -- The Ferengi Rules of Acquisition (DS9 reference book) ",
    "Money can't buy happiness, but it can make you awfully comfortable while you're being miserable. 		-- C. B. Luce ",
    "Bunker's Admonition: 	You cannot buy beer; you can only rent it. ",
    "Ask five economists and you'll get five different explanations (six if one went to Harvard). 		-- Edgar R. Fiedler ",
    "If God didn't mean for us to juggle, tennis balls wouldn't come three to a can. ",
    "All articles that coruscate with resplendence are not truly auriferous. ",
    "Mediocrity finds safety in standardization. 		-- Frederick Crane ",
    "You never learn anything by doing it right. ",
    "You will gain money by a speculation or lottery. ",
    "I like being single.  I'm always there when I need me. 		-- Art Leo ",
    "You have acquired a scroll entitled 'irk gleknow mizk'(n).--More--  This is an IBM Manual scroll.--More--  You are permanently confused. 		-- Dave Decot ",
    "... though his invention worked superbly -- his theory was a crock of sewage from beginning to end. 		-- Vernor Vinge, \"The Peace War\" ",
    "The Killer Ducks are coming!!! ",
    "Gee, Toto, I don't think we're in Kansas anymore. ",
    "The human race is a race of cowards; and I am not only marching in that procession but carrying a banner. 		-- Mark Twain ",
    "<Palisade> how are we going to pronounce '00 or '01 or '02 and so on? <Deek> Say goodbye to the nineties, say hello to the naughties. :) ",
    " \"Someone's been mean to you! Tell me who it is, so I can punch him tastefully.\" 		-- Ralph Bakshi's Mighty Mouse ",
    "\"I didn't know it was impossible when I did it.\" ",
    "Computers can figure out all kinds of problems, except the things in the world that just don't add up. ",
    "Parsley 	 is gharsley. 		-- Ogden Nash ",
    "Because we don't think about future generations, they will never forget us. 		-- Henrik Tikkanen ",
    "A wise man can see more from the bottom of a well than a fool can from a mountain top. ",
    "\"Here's something to think about:  How come you never see a headline like  `Psychic Wins Lottery.'\" 		-- Comedian Jay Leno ",
    "A journey of a thousand miles starts under one's feet. 		-- Lao Tsu ",
    "If it were not for the presents, an elopement would be preferable. 		-- George Ade, \"Forty Modern Fables\" ",
    "My friend has a baby.  I'm writing down all the noises he makes so later I can ask him what he meant. 		-- Steven Wright ",
    "If little else, the brain is an educational toy. 		-- Tom Robbins ",
    "Many are called, few volunteer. ",
    "<Coderjoe> gib, perl? <gib> methinks perl is the programmer's Swiss Army Chainsaw ",
    "A man without a woman is like a statue without pigeons. ",
    "Big book, big bore. 		-- Callimachus ",
    "We are all dying -- and we're gonna be dead for a long time. ",
    "What I need is a MATURE RELATIONSHIP with a FLOPPY DISK ... ",
    "Q:	What's the difference between USL and the Graf Zeppelin? A:	The Graf Zeppelin represented cutting edge technology for its time. ",
    "Try to be the best of whatever you are, even if what you are is no good. ",
    "A jury consists of twelve persons chosen to decide who has the better lawyer. 		-- Robert Frost ",
    "If God had not given us sticky tape, it would have been necessary to invent it. ",
    "Q:	How many mathematicians does it take to screw in a light bulb? A:	One.  He gives it to six Californians, thereby reducing the problem 	to the earlier joke. ",
    "Two percent of zero is almost nothing. ",
    "A journey of a thousand miles begins with a cash advance. ",
    "\"You can't make a program without broken egos.\" ",
];
