const fortunes = [
    "Ferengi Rule of Acquisition #75: Home is where the heart is - but the stars are made of latinum. -- Civil Defense (DS9 episode) ",
    "Rebellion lay in his way, and he found it. 		-- William Shakespeare, \"Henry IV\" ",
    "\"Every man has his price.  Mine is $3.95.\" ",
    "Renning's Maxim: 	Man is the highest animal.  Man does the classifying. ",
    "I cannot and will not cut my conscience to fit this year's fashions. 		-- Lillian Hellman ",
    "Young men want to be faithful and are not; old men want to be faithless and cannot. 		-- Oscar Wilde ",
    "\"I have five dollars for each of you.\" 		-- Bernhard Goetz ",
    "I stick my neck out for nobody. 		-- Humphrey Bogart, \"Casablanca\" ",
    "I'd rather just believe that it's done by little elves running around. ",
    "The sooner our happiness together begins, the longer it will last. 		-- Miramanee, \"The Paradise Syndrome\", stardate 4842.6 ",
    "The District of Columbia has a law forbidding you to exert pressure on a balloon and thereby cause a whistling sound on the streets. ",
    "If we see the light at the end of the tunnel, it's the light of an oncoming train. 		-- Robert Lowell ",
    "The knowledge that makes us cherish innocence makes innocence unattainable. 		-- Irving Howe ",
    "The first rule of all intelligent tinkering is to keep all the parts. 		-- Aldo Leopold, quoted in Donald Wurster's \"Nature's Economy\" ",
    "The trouble with being punctual is that nobody's there to appreciate it. 		-- Franklin P. Jones ",
    "War is never imperative. 		-- McCoy, \"Balance of Terror\", stardate 1709.2 ",
    "You are going to have a new love affair. ",
    "Clothes make the man.  Naked people have little or no influence on society. 		-- Mark Twain ",
    "Stupidity, like virtue, is its own reward. ",
    "The better the state is established, the fainter is humanity. To make the individual uncomfortable, that is my task. 		-- Nietzsche ",
    "\"All we are given is possibilities -- to make ourselves one thing or another.\" 		-- Ortega y Gasset ",
    "Logic is a little bird, sitting in a tree; that smells *awful*. ",
    "For the sake of argument I'll ignore all your fighting words. 		-- Larry Wall in <199710221710.KAA24242@wall.org> ",
    "Just because you like my stuff doesn't mean I owe you anything. 		-- Bob Dylan ",
    "I couldn't possibly fail to disagree with you less. ",
    "I have had my television aerials removed.  It's the moral equivalent of a prostate operation. 		-- Malcolm Muggeridge ",
    "\"You can have my Unix system when you pry it from my cold, dead fingers.\" 		-- Cal Keegan ",
    "It is exactly because a man cannot do a thing that he is a proper judge of it. 		-- Oscar Wilde ",
    "And we can always supply them with a program that makes identical files into links to a single file. 		-- Larry Wall in <199709292012.NAA09616@wall.org> ",
    "The things that interest people most are usually none of their business. ",
    "Violence is the last refuge of the incompetent. 		-- Salvor Hardin ",
    "I'm having a MID-WEEK CRISIS! ",
    "People who push both buttons should get their wish. ",
    "Rule of Creative Research: 	(1) Never draw what you can copy. 	(2) Never copy what you can trace. 	(3) Never trace what you can cut out and paste down. ",
    "There are three things I always forget.  Names, faces -- the third I can't remember. 		-- Italo Svevo ",
    "<dark> Culus: Building a five-meter-high replica of the Empire State        Building with paperclips is impressive.  Doing it blindfolded is        eleet. ",
    "It is impossible to enjoy idling thoroughly unless one has plenty of work to do. 		-- Jerome Klapka Jerome ",
    "QOTD: 	\"I won't say he's untruthful, but his wife has to call the 	dog for dinner.\" ",
    "Spring is here, spring is here, Life is skittles and life is beer. ",
    "If loving linux is wrong, I don't wanna be right. 	-- Topic for #LinuxGER ",
    "What's page one, a preemptive strike? 		-- Professor Freund, Communication, Ramapo State College ",
    "Machines have less problems.  I'd like to be a machine. 		-- Andy Warhol ",
    "Marriage is a ghastly public confession of a strictly private intention. ",
    "Nihilism should commence with oneself. ",
    "Thufir's a Harkonnen now. ",
    "Our problems are so serious that the best way to talk about them is lightheartedly. ",
    "Hey, wait a minute!!  I want a divorce!! ... you're not Clint Eastwood!! ",
    "Sanity is the trademark of a weak mind. 		-- Mark Harrold ",
    "In California they don't throw their garbage away -- they make it into television shows. 		-- Woody Allen, \"Annie Hall\" ",
    "Children aren't happy without something to ignore, And that's what parents were created for. 		-- Ogden Nash ",
    "The one charm of marriage is that it makes a life of deception a necessity. 		-- Oscar Wilde ",
    "QOTD: 	\"I may not be able to walk, but I drive from the sitting position.\" ",
    "When you say that you agree to a thing in principle, you mean that you have not the slightest intention of carrying it out in practice. 		-- Otto Von Bismarck ",
    "The angry man always thinks he can do more than he can. 		-- Albertano of Brescia ",
    "A sine curve goes off to infinity, or at least the end of the blackboard. 		-- Prof. Steiner ",
    "\"To YOU I'm an atheist; to God, I'm the Loyal Opposition.\" 		-- Woody Allen ",
    "\"They make a desert and call it peace.\" 		-- Tacitus (55?-120?) ",
    "You cannot kill time without injuring eternity. ",
    "Good day for overcoming obstacles.  Try a steeplechase. ",
    "Show me a man who is a good loser and I'll show you a man who is playing golf with his boss. ",
    "<dhd> perl < /dev/bdsm <knghtbrd> you have a /dev/bdsm? <dhd> sure, it's a pseudosadomasochistic random number generator ",
    "You can't expect a boy to be vicious till he's been to a good school. 		-- H. H. Munro ",
    "My darling wife was always glum. I drowned her in a cask of rum, And so made sure that she would stay In better spirits night and day. ",
    "We all like praise, but a hike in our pay is the best kind of ways. ",
    "Q:	What do you get when you cross the Godfather with an attorney? A:	An offer you can't understand. ",
    "<miguel> any new sendmail hole I have to fix before going on vacations? 	-- Seen on #Linux ",
    "To find out a girl's faults, praise her to her girl friends.  		-- Paraphrasing on Benjamin Franklin (see: 		https://en.wikiquote.org/wiki/Benjamin_Franklin ) ",
    "If you look good and dress well, you don't need a purpose in life. 		-- Robert Pante, fashion consultant ",
    "Absence diminishes mediocre passions and increases great ones, as the wind blows out candles and fans fires. 		-- La Rochefoucauld ",
    "teamwork, n.: 	Having someone to blame. ",
    "The days are all empty and the nights are unreal. ",
    "Genius is one percent inspiration and ninety-nine percent perspiration. 		-- Thomas Alva Edison ",
    "Sooner or later you must pay for your sins. (Those who have already paid may disregard this cookie). ",
    "We don't like their sound.  Groups of guitars are on the way out. 		-- Decca Recording Company, turning down the Beatles, 1962 ",
    "petribar: 	Any sun-bleached prehistoric candy that has been sitting in 	the window of a vending machine too long. 		-- Rich Hall, \"Sniglets\" ",
    "No matter what happens, there is always someone who knew it would. ",
    "Where you stand depends on where you sit. 		-- Rufus Miles, HEW ",
    "MIT: 	The Georgia Tech of the North ",
    "paranoia, n.: 	A healthy understanding of the way the universe works. ",
    "Life would be so much easier if we could just look at the source code. 		-- Dave Olson ",
    "The husband who doesn't tell his wife everything probably reasons that what she doesn't know won't hurt him. 		-- Leo J. Burke ",
    "<KnaraKat> DalNet is like the special olympics of IRC.  There's a lot of            drooling goin' on and everyone is a 'winner'. ",
    "Coding is easy;  All you do is sit staring at a terminal until the drops of blood form on your forehead. ",
    "Yes, but which self do you want to be? ",
    "Bernard Shaw is an excellent man; he has not an enemy in the world, and none of his friends like him either. 		-- Oscar Wilde ",
    "You know you're a little fat if you have stretch marks on your car. 		-- Cyrus, Chicago Reader 1/22/82 ",
    "Thus spake the master programmer: 	\"After three days without programming, life becomes meaningless.\" 		-- Geoffrey James, \"The Tao of Programming\" ",
    "<Espy> tomorrow there will be a great disturbance in the workforce 		-- May 18, 1999 ",
    "One good thing about music, Well, it helps you feel no pain. So hit me with music; Hit me with music now. 		-- Bob Marley, \"Trenchtown Rock\" ",
    "What is irritating about love is that it is a crime that requires an accomplice. 		-- Charles Baudelaire ",
    "\"Been through Hell?  Whaddya bring back for me?\" 		-- A. Brilliant ",
    "Excusing bad programming is a shooting offence, no matter _what_ the circumstances. 	-- Linus Torvalds, to the linux-kernel list ",
    "	\"Then you admit confirming not denying you ever said that?\" 	\"NO! ... I mean Yes!  WHAT?\" 	\"I'll put `maybe.'\" 		-- Bloom County ",
    "This TOPS OFF my partygoing experience!  Someone I DON'T LIKE is talking to me about a HEART-WARMING European film ... ",
    "<Culus> OH MY GOD NOT A RANDOM QUOTE GENERATOR <netgod> surely you didn't think that was static? how lame would that be? :-) ",
    "\"Security is mostly a superstition.  It does not exist in nature... Life is either a daring adventure or nothing.\" 		-- Helen Keller ",
    "When you dial a wrong number you never get a busy signal. ",
    "I just ate a whole package of Sweet Tarts and a can of Coke. I think I saw God. 		-- B. Hathrume Duk ",
    "You will have many recoverable tape errors. ",
    "When a fellow says, \"It ain't the money but the principle of the thing,\" it's the money. 		-- Kim Hubbard ",
    "PARDON me, am I speaking ENGLISH? ",
    "Marriage is an institution in which two undertake to become one, and one undertakes to become nothing. ",
    "Maybe we could paint GOLDIE HAWN a rich PRUSSIAN BLUE -- ",
    "Power corrupts.  Absolute power is kind of neat. 		-- John Lehman, Secretary of the Navy, 1981-1987 ",
    "Satire is what closes in New Haven. ",
    "A dream will always triumph over reality, once it is given the chance. 		-- Stanislaw Lem ",
    "Real Users never use the Help key. ",
    "We are not anticipating any emergencies. ",
    "\"I'd love to go out with you, but it's my parakeet's bowling night.\" ",
    "It's all magic.  :-) 		-- Larry Wall in <7282@jpl-devvax.JPL.NASA.GOV> ",
    "I don't want to be young again, I just don't want to get any older. ",
    "Money is better than poverty, if only for financial reasons. ",
    "If you put your supper dish to your ear you can hear the sounds of a restaurant. 		-- Snoopy ",
    "Are we on STRIKE yet? ",
    "Weinberg's Principle: 	An expert is a person who avoids the small errors while 	sweeping on to the grand fallacy. ",
    "\"No, `Eureka' is Greek for `This bath is too hot.'\" 		-- Dr. Who ",
    "It seems like the less a statesman amounts to, the more he loves the flag. ",
    "You don't have to explain something you never said. 		-- Calvin Coolidge ",
    "SUN Microsystems: 	The Network IS the Load Average. ",
    "A 'full' life in my experience is usually full only of other people's demands. ",
    "I suggest a new strategy, Artoo: let the Wookie win. 		-- C3P0 ",
    "... the MYSTERIANS are in here with my CORDUROY SOAP DISH!! ",
    "Linus' Law: 	There is no heavier burden than a great potential. ",
    "It does not matter if you fall down as long as you pick up something from the floor while you get up. ",
    "Mitchell's Law of Committees: 	Any simple problem can be made insoluble if enough meetings are 	held to discuss it. ",
    "God must love the common man; He made so many of them. ",
    "weapon, n.: 	An index of the lack of development of a culture. ",
    "Boys are beyond the range of anybody's sure understanding, at least when they are between the ages of 18 months and 90 years. 		-- James Thurber ",
    "To be who one is, is not to be someone else. ",
    "<wiggy> bwah, vodka in my mouse ",
    "I guess you guys got BIG MUSCLES from doing too much STUDYING! ",
    "I am not an Economist.  I am an honest man! 		-- Paul McCracken ",
    "Men never make passes at girls wearing glasses. 		-- Dorothy Parker ",
    "Your job is being a professor and researcher: That's one hell of a good excuse for some of the brain-damages of minix. 	-- Linus Torvalds to Andrew Tanenbaum ",
    "My friend has a baby.  I'm writing down all the noises he makes so later I can ask him what he meant. 		-- Steven Wright ",
    "When I met th'POPE back in '58, I scrubbed him with a MILD SOAP or DETERGENT for 15 minutes.  He seemed to enjoy it ... ",
    "\"The four building blocks of the universe are fire, water, gravel and vinyl.\" 		-- Dave Barry ",
    "* o-o always like debmake because he knew exactly what it would do... <ibid> o-o: you would ;-) ",
    "I was born in a Hostess Cupcake factory before the sexual revolution! ",
    "Whenever people agree with me I always feel I must be wrong. 		-- Oscar Wilde ",
    "Yes, but which self do you want to be? ",
    "Truth has no special time of its own.  Its hour is now -- always. 		-- Albert Schweitzer ",
    "Hello?  Enema Bondage?  I'm calling because I want to be happy, I guess ... ",
    "When you're ready to give up the struggle, who can you surrender to? ",
    "Arithmetic is being able to count up to twenty without taking off your shoes. 		-- Mickey Mouse ",
    "Stealing a rhinoceros should not be attempted lightly. ",
    "Blend until smooth. ",
    "Life is like bein' on a mule team.  Unless you're the lead mule, all the scenery looks about the same. ",
    "\"Mind if I smoke?\" 	\"Yes, I'd like to see that, does it come out of your ears or what?\" ",
    "My, how you've changed since I've changed. ",
    "It's not the valleys in life I dread so much as the dips. 		-- Garfield ",
    "The majority of husbands remind me of an orangutang trying to play the violin. 		-- Honore DeBalzac ",
    "Eloquence is logic on fire. ",
    "Love is in the offing.  Be affectionate to one who adores you. ",
    "Euch ist bekannt, was wir beduerfen; Wir wollen stark Getraenke schluerfen. 		-- Goethe, \"Faust\" ",
    "I never expected to see the day when girls would get sunburned in the places they do today. 		-- Will Rogers ",
    "I know it's weird, but it does make it easier to write poetry in perl.    :-) 		-- Larry Wall in <7865@jpl-devvax.JPL.NASA.GOV> ",
    "People who have what they want are very fond of telling people who haven't what they want that they don't want it. 		-- Ogden Nash ",
    "I hate small towns because once you've seen the cannon in the park there's nothing else to do. 		-- Lenny Bruce ",
    "Where's the Coke machine?  Tell me a joke!! ",
    "Some bird populations soaring down 	-Headline of an article in 	 Science News, page 126, February 20, 1993. ",
    "\"Elves and Dragons!\" I says to him.  \"Cabbages and potatoes are better for you and me.\" 		-- J. R. R. Tolkien ",
    "All men profess honesty as long as they can.  To believe all men honest would be folly.  To believe none so is something worse. 		-- John Quincy Adams ",
    "Satire does not look pretty upon a tombstone. ",
    "I would like to know What I was fencing in And what I was fencing out. 		-- Robert Frost ",
    "I don't care where I sit as long as I get fed. 		-- Calvin Trillin ",
    "Ferengi Rule of Acquisition #14: Sometimes the quickest way to find profits is to let them find you. -- Fortune of War (TTN novel) ",
    "Look!  A ladder!  Maybe it leads to heaven, or a sandwich! ",
    "The default Magic Word, \"Abracadabra\", actually is a corruption of the Hebrew phrase \"ha-Bracha dab'ra\" which means \"pronounce the blessing\". ",
    "I'll defend to the death your right to say that, but I never said I'd listen to it! 		-- Tom Galloway with apologies to Voltaire ",
    "momentum, n.: 	What you give a person when they are going away. ",
    "Steal this tagline.  I did. ",
    "Alive without breath, As cold as death; Never thirsty, ever drinking, All in mail never clinking. ",
    "Man has made his bedlam; let him lie in it. 		-- Fred Allen ",
    "God is dead and I don't feel all too well either.... 		-- Ralph Moonen ",
    "Ferengi Rule of Acquisition #289: A man is only worth the sum of his possessions. -- Acquisition (ENT episode) ",
    "- DDD no longer requires the librx library.  Consequently, librx   errors can no more cause DDD to crash. 	-- DDD ",
    "It's like deja vu all over again. 		-- Yogi Berra ",
    "Q:	Who cuts the grass on Walton's Mountain? A:	Lawn Boy. ",
    "To add insult to injury. 		-- Phaedrus ",
    "Tex SEX!  The HOME of WHEELS!  The dripping of COFFEE!!  Take me to Minnesota but don't EMBARRASS me!! ",
    "Monday is an awful way to spend one seventh of your life. ",
    "<Knghtbrd> Leave it to manoj to call procmail \"puny\" ",
    "The more control, the more that requires control. ",
    "It is better to die on your feet than to live on your knees. ",
    "This is a scsi driver, scraes the shit out of me, therefore I tapdanced and wrote a unix clone around it (C) by linus 	-- Somewhere in the kernel tree ",
    "Ferengi Rule of Acquisition #216: Never gamble with a telepath. -- The Laertian Gamble (DS9 novel) ",
    "Words can never express what words can never express. ",
    "Now is the time for drinking; now the time to beat the earth with unfettered foot. 		-- Quintus Horatius Flaccus (Horace) ",
    "Success is something I will dress for when I get there, and not until. ",
    "\"Can't you just gesture hypnotically and make him disappear?\"     \"It does not work that way.  RUN!\" 		-- Hadji on metaphysics and Mandrake in \"Jonny Quest\" ",
    "Above all else -- sky. ",
    "Genius, n.: 	A chemist who discovers a laundry additive that rhymes with \"bright.\" ",
    "\"The Lord gave us farmers two strong hands so we could grab as much as we could with both of them.\" 		-- Joseph Heller, \"Catch-22\" ",
    "Regardless of whether a mission expands or contracts, administrative overhead continues to grow at a steady rate. ",
    "\"Rembrandt's first name was Beauregard, which is why he never used it.\" 		-- Dave Barry ",
    "giraffiti: 	Vandalism spray-painted very, very high. ",
    "The rose of yore is but a name, mere names are left to us. ",
    "QOTD: 	\"It's a cold bowl of chili, when love don't work out.\" ",
    "\"Is it really you, Fuzz, or is it Memorex, or is it radiation sickness?\" 		-- Sonic Disruptors comics ",
    "But they went to MARS around 1953!! ",
    "Nothing is as simple as it seems at first 	Or as hopeless as it seems in the middle 		Or as finished as it seems in the end. ",
    "Baker's First Law of Federal Geometry: 	A block grant is a solid mass of money surrounded on all sides by 	governors. ",
    "YOW!!  What should the entire human race DO??  Consume a fifth of CHIVAS REGAL, ski NUDE down MT. EVEREST, and have a wild SEX WEEKEND! ",
    "The so-called lessons of history are for the most part the rationalizations of the victors.  History is written by the survivors. 		-- Max Lerner ",
    "I program, therefore I am. ",
    "And furthermore, my bowling average is unimpeachable!!! ",
    "E Pluribus Unix ",
    "Trifles make perfection, and perfection is no trifle. 		-- Michelangelo ",
    "There are only two kinds of tequila.  Good and better. ",
    "Send your questions to ``ASK ZIPPY'', Box 40474, San Francisco, CA 94140, USA ",
    "<Deek> change all cvar->value = X to use Cvar_Set() <theoddone33> that didn't happen in oldtree <Deek> Actually, it did. <Knghtbrd> yeah - two weeks later. ",
    "Clones are people two. ",
    "A girl's conscience doesn't really keep her from doing anything wrong-- it merely keeps her from enjoying it. ",
    "A father doesn't destroy his children. 		-- Lt. Carolyn Palamas, \"Who Mourns for Adonais?\", 		   stardate 3468.1. ",
    "Package sold by weight, not volume. ",
    "My philosophy is: Don't think. 		-- Charles Manson ",
    "* Knghtbrd crosses his toes <Knghtbrd> (if I crossed my fingers it would be hard to type) ",
    "Anything anybody can say about America is true. 		-- Emmett Grogan ",
    "Mater artium necessitas. 	[Necessity is the mother of invention]. ",
    "Save a little money each month and at the end of the year you'll be surprised at how little you have. 		-- Ernest Haskins ",
    "When some people decide it's time for everyone to make big changes, it means that they want you to change first. ",
    "A woman can look both moral and exciting -- if she also looks as if it were quite a struggle. 		-- Edna Ferber ",
    "The most disagreeable thing that your worst enemy says to your face does not approach what your best friends say behind your back. 		-- Alfred De Musset ",
    "Too much of everything is just enough. 		-- Bob Wier ",
    "If life gives you lemons, make lemonade. ",
    "One picture is worth 128K words. ",
    "Any time things appear to be going better, you have overlooked something. ",
    "HOORAY, Ronald!!  Now YOU can marry LINDA RONSTADT too!! ",
    "Order and simplification are the first steps toward mastery of a subject -- the actual enemy is the unknown. 		-- Thomas Mann ",
    "The more they over-think the plumbing the easier it is to stop up the drain. ",
    "Loni Anderson's hair should be LEGALIZED!! ",
    "I guess the Little League is even littler than we thought. 		-- D. Cavett ",
    "Sho' they got to have it against the law.  Shoot, ever'body git high, they wouldn't be nobody git up and feed the chickens.  Hee-hee. 		-- Terry Southern ",
    "\"The geeks shall inherit the earth.\" 		-- Karl Lehenbauer ",
    "Do not worry about which side your bread is buttered on: you eat BOTH sides. ",
    "You ask what a nice girl will do?  She won't give an inch, but she won't say no. 		-- Marcus Valerius Martialis ",
    "Example is not the main thing in influencing others.  It is the only thing. 		-- Albert Schweitzer ",
    "\"Jesus saves...but Gretzky gets the rebound!\" 		-- Daniel Hinojosa (hinojosa@hp-sdd) ",
    "The best prophet of the future is the past. ",
    "For great justice.     -- Cut scene from the game \"Zero Wing\"     -- https://en.wikipedia.org/wiki/All_your_base_are_belong_to_us ",
    "<knghtbrd> Nintendo Declares GCN Most Popular Console Ever <knghtbrd> Who are they kidding? <Mercury> knghtbrd: Stock holders? ",
    "Take a lesson from the whale; the only time he gets speared is when he raises to spout. ",
    "I will not forget you. ",
    "HUMAN REPLICAS are inserted into VATS of NUTRITIONAL YEAST ... ",
    "Did you know ...  That no-one ever reads these things? ",
    "Creativity is not always bred in an environment of tranquility; sometimes you have to squeeze a little to get the paste out of the tube. ",
    "\"By the time they had diminished from 50 to 8, the other dwarves began to suspect \"Hungry.\" 		-- a Larson cartoon ",
    "Most people prefer certainty to truth. ",
    "QOTD: 	\"I don't think they could put him in a mental hospital.  On the 	other hand, if he were already in, I don't think they'd let him out.\" ",
    "statistics, n.: 	A system for expressing your political prejudices in convincing 	scientific guise. ",
    "\"We will bury you.\" 		-- Nikita Kruschev ",
    "Steckel's Rule to Success: 	Good enough is never good enough. ",
    "In case of fire, stand in the hall and shout \"Fire!\" 		-- The Kidner Report ",
    "Democracy is a form of government that substitutes election by the incompetent many for appointment by the corrupt few. 		-- G. B. Shaw ",
    "In the Halls of Justice the only justice is in the halls. 		-- Lenny Bruce ",
    "Hanlon's Razor: 	Never attribute to malice that which is adequately explained 	by stupidity. ",
    "No problem is insoluble. 		-- Dr. Janet Wallace, \"The Deadly Years\", stardate 3479.4 ",
    "Of course you have a purpose -- to find a purpose. ",
    "I don't mind what Congress does, as long as they don't do it in the streets and frighten the horses. 		-- Victor Hugo ",
    "Loud burping while walking around the airport is prohibited in Halstead, Kansas. ",
    "-- I love KATRINKA because she drives a PONTIAC.  We're going away now.  I fed the cat. ",
    "You are so boring that when I see you my feet go to sleep. ",
    "Nothing is so firmly believed as that which we least know. 		-- Michel de Montaigne ",
    "The world is full of people who have never, since childhood, met an open doorway with an open mind. 		-- E. B. White ",
    "Don't go to bed with no price on your head. 		-- Baretta ",
    "Every absurdity has a champion who will defend it. ",
    "Of course it's the murder weapon.  Who would frame someone with a fake? ",
    "Good advice is one of those insults that ought to be forgiven. ",
    "Marriage is the only adventure open to the cowardly. 		-- Voltaire ",
    "Good advice is one of those insults that ought to be forgiven. ",
    "The trouble with being punctual is that nobody's there to appreciate it. 		-- Franklin P. Jones ",
    "I'm continually AMAZED at th'breathtaking effects of WIND EROSION!! ",
    "Real Programmers think better when playing Adventure or Rogue. ",
    "When women kiss it always reminds one of prize fighters shaking hands. 		-- H. L. Mencken, \"Sententiae\" ",
    "Some restrictions may apply. ",
    "Hard reality has a way of cramping your style. 		-- Daniel Dennett ",
    "\"How to make a million dollars:  First, get a million dollars.\" 		-- Steve Martin ",
    "Coming together is a beginning; 	keeping together is progress; 		working together is success. ",
    "My mother is a fish. 		-- William Faulkner ",
    "If I pull this SWITCH I'll be RITA HAYWORTH!!  Or a SCIENTOLOGIST! ",
    "To do nothing is to be nothing. ",
    "The good (I am convinced, for one) Is but the bad one leaves undone. Once your reputation's done You can live a life of fun. 		-- Wilhelm Busch ",
    "Computers are not intelligent.  They only think they are. ",
    "QOTD: 	\"There may be no excuse for laziness, but I'm sure looking.\" ",
    "I stopped a long time ago to try to find anything in the bug list of dpkg. We should run for an entry in the Guinness Book of Records. 		-- Stephane Bortzmeyer ",
    "A journey of a thousand miles begins with a cash advance. ",
    "I find you lack of faith in the forth dithturbing. 		-- Darse (\"Darth\") Vader ",
    "If you can't be good, be careful.  If you can't be careful, give me a call. ",
    "\"I'm a mean green mother from outer space\" 		-- Audrey II, The Little Shop of Horrors ",
    "The meek shall inherit the Earth.  (But they're gonna have to fight for it.) ",
    "Pass with care. ",
    "Nice guys finish last. 		-- Leo Durocher ",
    "You will have long and healthy life. ",
    "Sun in the night, everyone is together, Ascending into the heavens, life is forever. 		-- Brand X, \"Moroccan Roll/Sun in the Night\" ",
    "The difficult we do today; the impossible takes a little longer. ",
    "If God had meant for us to be naked, we would have been born that way. ",
    "You have acquired a scroll entitled 'irk gleknow mizk'(n).--More--  This is an IBM Manual scroll.--More--  You are permanently confused. 		-- Dave Decot ",
    "Marriages are made in heaven and consummated on earth. 		-- John Lyly ",
    "Troubles are like babies; they only grow by nursing. ",
    "Too much is not enough. ",
    "<Mercury> At that point it will compile, but segfault, as it should.. ",
    "Misuse may cause suffocation. ",
    "\"Anyone attempting to generate random numbers by deterministic means is, of course, living in a state of sin.\" 		-- John Von Neumann ",
    "\"Our reruns are better than theirs.\" 		-- Nick at Nite ",
    "Newman's Discovery: 	Your best dreams may not come true; fortunately, neither will 	your worst dreams. ",
    "When the fog came in on little cat feet last night, it left these little muddy paw prints on the hood of my car. ",
    "How many hardware guys does it take to change a light bulb?  \"Well the diagnostics say it's fine buddy, so it's a software problem.\" ",
    "\"Where humor is concerned there are no standards -- no one can say what is good or bad, although you can be sure that everyone will.  -- John Kenneth Galbraith ",
    "Innovation distinguishes between a leader and a follower.                 -- Steve Jobs (1955-2011) ",
    "Intuition, however illogical, is recognized as a command prerogative. 		-- Kirk, \"Obsession\", stardate 3620.7 ",
    "The louder he talked of his honour, the faster we counted our spoons. 		-- Ralph Waldo Emerson ",
    "Lowery's Law: 	If it jams -- force it.  If it breaks, it needed replacing anyway. ",
    "Four fifths of the perjury in the world is expended on tombstones, women and competitors. 		-- Lord Thomas Dewar ",
    "They will only cause the lower classes to move about needlessly. 		-- The Duke of Wellington, on early steam railroads. ",
    "This message was written with vi!  (not that anyone in the world cares) 		-- seen on an old message from an anon.penet.fi address ",
    "Your lover will never wish to leave you. ",
    "A rolling stone gathers momentum. ",
    "Death before dishonor.  But neither before breakfast. ",
    "The wonderful thing about a dancing bear is not how well he dances, but that he dances at all. ",
    "After the game the king and the pawn go in the same box. 		-- Italian proverb ",
    "Maybe Computer Science should be in the College of Theology. 		-- R. S. Barton ",
    "Approved for veterans. ",
    "Courage is your greatest present need. ",
    "The IBM 2250 is impressive ... if you compare it with a system selling for a tenth its price. 		-- D. Cohen ",
    "Q:	How many IBM CPU's does it take to do a logical right shift? A:	33.  1 to hold the bits and 32 to push the register. ",
    "I'm QUIETLY reading the latest issue of \"BOWLING WORLD\" while my wife and two children stand QUIETLY BY ... ",
    "\"It is easier to port a shell than a shell script.\" 		-- Larry Wall ",
    "The wonderful thing about a dancing bear is not how well he dances, but that he dances at all. ",
    "You have been selected for a secret mission. ",
    "You are farsighted, a good planner, an ardent lover, and a faithful friend. ",
    "\"Atomic batteries to power, turbines to speed.\" 		-- Robin, The Boy Wonder ",
    "All your people must learn before you can reach for the stars. 		-- Kirk, \"The Gamesters of Triskelion\", stardate 3259.2 ",
    "Go on, EMOTE!  I was RAISED on thought balloons!! ",
    "Q:	What do you call the scratches that you get when a female 	sheep bites you? A:	Ewe nicks. ",
    "... the MYSTERIANS are in here with my CORDUROY SOAP DISH!! ",
    "Substantial risk of electric shock. ",
    "Those who do not understand Unix are condemned to reinvent it, poorly. 		-- Henry Spencer ",
    "The less a statesman amounts to, the more he loves the flag. 		-- Kin Hubbard ",
    "Most public domain software is free, at least at first glance. ",
    "On the road, ZIPPY is a pinhead without a purpose, but never without a POINT. ",
    "Ferengi Rule of Acquisition #235: Duck - death is tall. -- Mission Gamma: Twilight (DS9 novel) ",
    "Ferengi Rule of Acquisition #63: Work is the best therapy - at least for your employees. -- Over a Torrent Sea (TTN novel) ",
    "Do not remove tag under penalty of law. ",
    "Remember Darwin; building a better mousetrap merely results in smarter mice. ",
    "Do your part to help preserve life on Earth -- by trying to preserve your own. ",
    "Old age and treachery will overcome youth and skill. ",
    "A person forgives only when they are in the wrong. ",
    "A couch is as good as a chair. ",
    "Q:	What do you call the scratches that you get when a female 	sheep bites you? A:	Ewe nicks. ",
    "\"What people have been reduced to are mere 3-D representations of their own data.\" 		-- Arthur Miller ",
    "Disk crisis, please clean up! ",
    "The Marines: 	The few, the proud, the not very bright. ",
    "My mother was a test tube; my father was a knife. 		-- Friday ",
    "Every man thinks God is on his side.  The rich and powerful know that he is. 		-- Jean Anouilh, \"The Lark\" ",
    "Limited delivery area. ",
    "I'm frequently appalled by the low regard you Earthmen have for life. 		-- Spock, \"The Galileo Seven\", stardate 2822.3 ",
    "One way to make your old car run better is to look up the price of a new model. ",
    "You'll never see all the places, or read all the books, but fortunately, they're not all recommended. ",
    "I'm so miserable without you, it's almost like you're here. ",
    "Money isn't everything -- but it's a long way ahead of what comes next. 		-- Sir Edmond Stockdale ",
    "The only difference between a rut and a grave is their dimensions. ",
    "You definitely intend to start living sometime soon. ",
    "Say it with flowers, Or say it with mink, But whatever you do, Don't say it with ink! 		-- Jimmie Durante ",
    "I will never lie to you. ",
    "If we men married the women we deserved, we should have a very bad time of it. 		-- Oscar Wilde ",
    "If you lose a son you can always get another, but there's only one Maltese Falcon. 		-- Sidney Greenstreet, \"The Maltese Falcon\" ",
    "Buckle up! ",
    "I B M U B M We all B M For I B M!!!! 		-- H.A.R.L.I.E. ",
    "Dijkstra probably hates me. 	-- Linus Torvalds, in kernel/sched.c ",
    "Beware of a tall blond man with one black shoe. ",
    "Reporter (to Mahatma Gandhi): Mr Gandhi, what do you think of Western 	Civilization? Gandhi:	I think it would be a good idea. ",
    "\"Why should we subsidize intellectual curiosity?\"  -Ronald Reagan ",
    "I think $[ is more like a coelacanth than a mastadon. 		-- Larry Wall in <199705101952.MAA00756@wall.org> ",
    "You will visit the Dung Pits of Glive soon. ",
    "Oh, love is real enough, you will find it some day, but it has one arch-enemy -- and that is life. 		-- Jean Anouilh, \"Ardele\" ",
    "This fortune intentionally not included. ",
    "Don't go around saying the world owes you a living.  The world owes you nothing.  It was here first. 		-- Mark Twain ",
    "Imitation is the sincerest form of plagiarism. ",
    "NEWARK has been REZONED!!  DES MOINES has been REZONED!! ",
    "We are all so much together and yet we are all dying of loneliness. 		-- A. Schweitzer ",
    "Approved for veterans. ",
    "The sooner you fall behind, the more time you have to catch up. ",
    "Quack! 	Quack!! Quack!! ",
    "It wasn't exactly a divorce -- I was traded. 		-- Tim Conway ",
    "When people say nothing, they don't necessarily mean nothing. ",
    "\"In order to make an apple pie from scratch, you must first create the universe.\" 		-- Carl Sagan, Cosmos ",
    "College: 	The fountains of knowledge, where everyone goes to drink. ",
    "All bridge hands are equally likely, but some are more equally likely than others. 		-- Alan Truscott ",
    "The two oldest professions in the world have been ruined by amateurs. 		-- G. B. Shaw ",
    "As Will Rogers would have said, \"There is no such things as a free variable.\" ",
    "Reader, suppose you were an idiot.  And suppose you were a member of Congress.  But I repeat myself. 		-- Mark Twain ",
    "Lie, n.: 	A very poor substitute for the truth, but the only one 	discovered to date. ",
    "War spares not the brave, but the cowardly. 		-- Anacreon ",
    "Microwaves frizz your heir. ",
    "\"Not Hercules could have knock'd out his brains, for he had none.\" 		-- Shakespeare ",
    "In the eyes of my dog, I'm a man. 		-- Martin Mull ",
    "Happiness is the greatest good. ",
    "In this world, nothing is certain but death and taxes. 		-- Benjamin Franklin ",
    "Celebrity voices impersonated. ",
    "The universe is all a spin-off of the Big Bang. ",
    "Be cheerful while you are alive. 		-- Phathotep, 24th Century B.C. ",
    "To do two things at once is to do neither. 		-- Publilius Syrus ",
    "Eighty percent of married men cheat in America.  The rest cheat in Europe. 		-- Jackie Mason ",
    "Only two of my personalities are schizophrenic, but one of them is paranoid and the other one is out to get him. ",
    "Have at you! ",
    "It is indeed desirable to be well descended, but the glory belongs to our ancestors. 		-- Plutarch ",
    "Three hours a day will produce as much as a man ought to write. 		-- Trollope ",
    "!07/11 PDP a ni deppart m'I  !pleH ",
    "Two wrongs don't make a right, but three lefts do. ",
    "\"World conquerors sometimes become fools, but fools never become world conquerors.\" 		-- \"The Outer Limits: The Invisibles\" ",
    "The ripest fruit falls first. 		-- William Shakespeare, \"Richard II\" ",
    "In the misfortune of our friends we find something that is not displeasing to us. 		-- La Rochefoucauld, \"Maxims\" ",
    "I thought YOU silenced the guard! ",
    "Paul Revere was a tattle-tale. ",
    "It was one of those perfect summer days -- the sun was shining, a breeze was blowing, the birds were singing, and the lawn mower was broken ... 		-- James Dent ",
    "Newman's Discovery: 	Your best dreams may not come true; fortunately, neither will 	your worst dreams. ",
    "The most happy marriage I can imagine to myself would be the union of a deaf man to a blind woman. 		-- Samuel Taylor Coleridge ",
    "I have a map of the United States.  It's actual size.  I spent last summer folding it.  People ask me where I live, and I say, \"E6\". 		-- Steven Wright ",
    "One nice thing about egotists: they don't talk about other people. ",
    "The young lady had an unusual list, Linked in part to a structural weakness. She set no preconditions. ",
    "A woman without a man is like a fish without a bicycle. 		-- Gloria Steinem ",
    "One of the worst of my many faults is that I'm too critical of myself. ",
    "I go on working for the same reason a hen goes on laying eggs. 		-- H. L. Mencken ",
    "\"Ignorance is the soil in which belief in miracles grows.\" 		-- Robert G. Ingersoll ",
    "You will be run over by a beer truck. ",
    "Ferengi Rule of Acquisition #123: Even a blind man can recognize the glow of latinum. -- The Ferengi Rules of Acquisition (DS9 reference book) ",
    "You'll be called to a post requiring ability in handling groups of people. ",
    "Fortune finishes the great quotations, #21  	Shall I compare thee to a Summer day? 	No, I guess not. ",
    "For 20 dollars, I'll give you a good fortune next time ... ",
    "Your domestic life may be harmonious. ",
    "Caution: breathing may be hazardous to your health. ",
    "The future is a myth created by insurance salesmen and high school counselors. ",
    "I HAVE to buy a new \"DODGE MISER\" and two dozen JORDACHE JEANS because my viewscreen is \"USER-FRIENDLY\"!! ",
    "Rebellion lay in his way, and he found it. 		-- William Shakespeare, \"Henry IV\" ",
    "Finding out what goes on in the C.I.A. is like performing acupuncture on a rock. 		-- New York Times, Jan. 20, 1981 ",
    "Catharsis is something I associate with pornography and crossword puzzles. 		-- Howard Chaykin ",
    "The one good thing about repeating your mistakes is that you know when to cringe. ",
    "Nothing succeeds like excess. 		-- Oscar Wilde ",
    "Nullum magnum ingenium sine mixtura dementiae fuit. 	[There is no great genius without some touch of madness.] 		-- Seneca ",
    "If I cannot bend Heaven, I shall move Hell. 		-- Publius Vergilius Maro (Virgil) ",
    "The next person to mention spaghetti stacks to me is going to have his head knocked off. 		-- Bill Conrad ",
    "	A shy teenage boy finally worked up the nerve to give a gift to Madonna, a young puppy.  It hitched its waggin' to a star. ",
    "Silence is the only virtue you have left. ",
    "QOTD: 	\"Of course it's the murder weapon.  Who would frame someone with 	a fake?\" ",
    "\"I'm in Pittsburgh.  Why am I here?\" 		-- Harold Urey, Nobel Laureate ",
    "Must be over 21. ",
    "Do students of Zen Buddhism do Om-work? ",
    "You will gain money by a speculation or lottery. ",
    "PLEASE DON'T SMOKE HERE!  Penalty: An early, lingering death from cancer, 	 emphysema, or other smoking-caused ailment. ",
    "For those who like this sort of thing, this is the sort of thing they like. 		-- Abraham Lincoln ",
    "Ours is a world of nuclear giants and ethical infants. 		-- General Omar N. Bradley ",
    "\"If the King's English was good enough for Jesus, it's good enough for me!\" 		-- \"Ma\" Ferguson, Governor of Texas (circa 1920) ",
    "I predict that today will be remembered until tomorrow! ",
    "Multics is security spelled sideways. ",
    "\"MacDonald has the gift on compressing the largest amount of words into the smallest amount of thoughts.\" 		-- Winston Churchill ",
    "Keep your eyes wide open before marriage, half shut afterwards. 		-- Benjamin Franklin ",
    "Hotels are tired of getting ripped off.  I checked into a hotel and they had towels from my house. 		-- Mark Guido ",
    "* bma is a yank * Knghtbrd is a Knghtbrd * dhd is also a yank * Espy is evil * Knghtbrd believes Espy ",
    "senility, n.: 	The state of mind of elderly persons with whom one happens to disagree. ",
    "Being a mime means never having to say you're sorry. ",
    "love, n.: 	When it's growing, you don't mind watering it with a few tears. ",
    "Don't panic. ",
    "Old men are fond of giving good advice to console themselves for their inability to set a bad example. 		-- La Rochefoucauld, \"Maxims\" ",
    "s = (char*)(long)retval;                /* ouch */ 		-- Larry Wall in doio.c from the perl source code ",
    "\"Of course power tools and alcohol don't mix.  Everyone knows power tools aren't soluble in alcohol...\" 		-- Crazy Nigel ",
    "To laugh at men of sense is the privilege of fools. ",
    "I never said all Democrats were saloonkeepers; what I said was all saloonkeepers were Democrats. ",
    "Best of all is never to have been born.  Second best is to die soon. ",
    "Yow!  Those people look exactly like Donnie and Marie Osmond!! ",
    "Protect from light. ",
    "\"I'd love to go out with you, but it's my parakeet's bowling night.\" ",
    "Your program is sick!  Shoot it and put it out of its memory. ",
    "Kaufman's Law: 	A policy is a restrictive document to prevent a recurrence 	of a single incident, in which that incident is never mentioned. ",
    "Pray to God, but keep rowing to shore. 		-- Russian Proverb ",
    "Let us treat men and women well; Treat them as if they were real; Perhaps they are. 		-- Ralph Waldo Emerson ",
    "The 11 is for people with the pride of a 10 and the pocketbook of an 8. 		-- R. B. Greenberg [referring to PDPs?] ",
    "Whereof one cannot speak, thereof one must be silent. 		-- Wittgenstein ",
    "If you push the \"extra ice\" button on the soft drink vending machine, you won't get any ice.  If you push the \"no ice\" button, you'll get ice, but no cup. ",
    "But you have to allow a little for the desire to evangelize when you think you have good news. 		-- Larry Wall in <1992Aug26.184221.29627@netlabs.com> ",
    "Thus spake the master programmer: 	\"When a program is being tested, it is too late to make design changes.\" 		-- Geoffrey James, \"The Tao of Programming\" ",
    "You are in the hall of the mountain king. ",
    "A celebrity is a person who is known for his well-knownness. ",
    "\"Here comes Mr. Bill's dog.\" 		-- Narrator, Saturday Night Live ",
    "The more you sweat in peace, the less you bleed in war. ",
    "Apathy Club meeting this Friday.  If you want to come, you're not invited. ",
    "Everybody likes a kidder, but nobody lends him money. 		-- Arthur Miller ",
    "Unnamed Law: 	If it happens, it must be possible. ",
    "         EARTH      smog  |   bricks  AIR  --  mud  --  FIRE soda water |   tequila          WATER ",
    "We have only two things to worry about:  That things will never get back to normal, and that they already have. ",
    "I never loved another person the way I loved myself. 		-- Mae West ",
    "You're being followed.  Cut out the hanky-panky for a few days. ",
    "Ask not for whom the <CONTROL-G> tolls. ",
    "Gordon's Law: 	If you think you have the solution, the question was poorly phrased. ",
    "It is illegal to say \"Oh, Boy\" in Jonesboro, Georgia. ",
    "Please recycle. ",
    "(1) Everything depends. (2) Nothing is always. (3) Everything is sometimes. ",
    "Ernest asks Frank how long he has been working for the company. 	\"Ever since they threatened to fire me.\" ",
    "Conformity is the refuge of the unimaginative. ",
    "There are no great men, only great challenges that ordinary men are forced by circumstances to meet. 		-- Admiral William Halsey ",
    "	\"Have you lived here all your life?\" 	\"Oh, twice that long.\" ",
    "Virtue is a relative term. 		-- Spock, \"Friday's Child\", stardate 3499.1 ",
    "Quidquid latine dictum sit, altum videtur. 	[Whatever is said in Latin sounds profound.] ",
    "Work continues in this area. 		-- DEC's SPR-Answering-Automaton ",
    "New England Life, of course.  Why do you ask? ",
    "\"Gee, Toto, I don't think we are in Kansas anymore.\" ",
    "The speed of anything depends on the flow of everything. ",
    "You will overcome the attacks of jealous associates. ",
    "Ummm, well, OK.  The network's the network, the computer's the computer. Sorry for the confusion. 		-- Sun Microsystems ",
    "I guess it was all a DREAM ... or an episode of HAWAII FIVE-O ... ",
    "The price of success in philosophy is triviality. 		-- C. Glymour. ",
    "Absence makes the heart grow fonder -- of somebody else. ",
];
function getRandomFortune() { return fortunes[Math.floor(Math.random() * fortunes.length)]; }
