const fortunes = [
    "It usually takes more than three weeks to prepare a good impromptu speech. 		-- Mark Twain ",
    "A debugged program is one for which you have not yet found the conditions that make it fail. 		-- Jerry Ogdin ",
    "Be circumspect in your liaisons with women.  It is better to be seen at the opera with a man than at mass with a woman. 		-- De Maintenon ",
    "This fortune would be seven words long if it were six words shorter. ",
    "...[Linux's] capacity to talk via any medium except smoke signals. 	-- Dr. Greg Wettstein, Roger Maris Cancer Center ",
    "Youth had been a habit of hers so long that she could not part with it. ",
    "One of the lessons of history is that nothing is often a good thing to do and always a clever thing to say. 		-- Will Durant ",
    "Serenity through viciousness. ",
    "IF I HAD A MINE SHAFT, I don't think I would just abandon it.  There's got to be a better way. 		-- Jack Handey, The New Mexican, 1988. ",
    "\"The four building blocks of the universe are fire, water, gravel and vinyl.\" 		-- Dave Barry ",
    "IBM Advanced Systems Group -- a bunch of mindless jerks, who'll be first against the wall when the revolution comes... 		-- with regrets to D. Adams ",
    "You will be aided greatly by a person whom you thought to be unimportant. ",
    "A celebrity is a person who is known for his well-knownness. ",
    "reintarnation: 	Coming back to life as a hillbilly. ",
    "Success is in the minds of Fools. 		-- William Wrenshaw, 1578 ",
    "The Korean War must have been fun. ",
    "Your fly might be open (but don't check it just now). ",
    "Convention is the ruler of all. 		-- Pindar ",
    "The truth of a proposition has nothing to do with its credibility.  And vice versa. ",
    "Q:	What lies on the bottom of the ocean and twitches? A:	A nervous wreck. ",
    "System going down at 5 this afternoon to install scheduler bug. ",
    "<Mercury> You don't have to be crazy to be a member of the project, but           you will be.. <=:] ",
    "Before destruction a man's heart is haughty, but humility goes before honour. 		-- Proverbs 18:12 ",
    "The idea of male and female are universal constants. 		-- Kirk, \"Metamorphosis\", stardate 3219.8 ",
    "Two is company, three is an orgy. ",
    "Sleep is for the weak and sickly. ",
    "VMS is like a nightmare about RXS-11M. ",
    "A subversive is anyone who can out-argue their government. ",
    "It were not best that we should all think alike; it is difference of opinion that makes horse-races. 		-- Mark Twain, \"Pudd'nhead Wilson's Calendar\" ",
    "She's genuinely bogus. ",
    "A light wife doth make a heavy husband. 		-- Wm. Shakespeare, \"The Merchant of Venice\" ",
    "Hope not, lest ye be disappointed. 		-- M. Horner ",
    "He:	Let's end it all, bequeathin' our brains to science. She:	What?!?  Science got enough trouble with their OWN brains. 		-- Walt Kelly ",
    "Prediction is very difficult, especially of the future. 		-- Niels Bohr ",
    "Computer Science is merely the post-Turing decline in formal systems theory. ",
    "You will be aided greatly by a person whom you thought to be unimportant. ",
    "Hindsight is always 20:20. 		-- Billy Wilder ",
    "pos += screamnext[pos]  /* does this goof up anywhere? */ 		-- Larry Wall in util.c from the perl source code ",
    "L'etat c'est moi. 	[I am the state.] 		-- Louis XIV ",
    "Very few profundities can be expressed in less than 80 characters. ",
    "The strong give up and move away, while the weak give up and stay. ",
    "<dpg> americans are weird.... <xtifr> californians even weirder <Knghtbrd> xtifr has a point ... ",
    "There is only one way to console a widow.  But remember the risk. 		-- Robert Heinlein ",
    "<aj> come on <aj> it's a pico clone <aj> it's *meant* to be annoying ",
    "The so-called lessons of history are for the most part the rationalizations of the victors.  History is written by the survivors. 		-- Max Lerner ",
    "I'm ZIPPY the PINHEAD and I'm totally committed to the festive mode. ",
    "Life without caffeine is stimulating enough. 		-- Sanka Ad ",
    "What I tell you three times is true. 		-- Lewis Carroll ",
    "If you can lead it to water and force it to drink, it isn't a horse. ",
    "Still looking for the glorious results of my misspent youth.  Say, do you have a map to the next joint? ",
    "People usually get what's coming to them ... unless it's been mailed. ",
    "Don't be irreplaceable, if you can't be replaced, you can't be promoted. ",
    "Emerson's Law of Contrariness: 	Our chief want in life is somebody who shall make us do what we 	can.  Having found them, we shall then hate them for it. ",
    "Marriage is the triumph of imagination over intelligence.  Second marriage is the triumph of hope over experience. ",
    "Telephone, n.: 	An invention of the devil which abrogates some of the advantages 	of making a disagreeable person keep his distance. 		-- Ambrose Bierce ",
    "Debug is human, de-fix divine. ",
    "One father is more than a hundred schoolmasters. 		-- George Herbert ",
    "Most rock journalism is people who can't write interviewing people who can't talk for people who can't read. 		-- Frank Zappa ",
    "While you recently had your problems on the run, they've regrouped and are making another attack. ",
    "Demand the establishment of the government in its rightful home at Disneyland. ",
    "I haven't lost my mind; I know exactly where I left it. ",
    "Santa's elves are just a bunch of subordinate Clauses. ",
    "Just because you like my stuff doesn't mean I owe you anything. 		-- Bob Dylan ",
    "Old Grandad is dead but his spirits live on. ",
    "Tuesday is the Wednesday of the rest of your life. ",
    "Who's scruffy-looking? 		-- Han Solo ",
    "(1) Never draw what you can copy. (2) Never copy what you can trace. (3) Never trace what you can cut out and paste down. ",
    "Being a mime means never having to say you're sorry. ",
    "The magic of our first love is our ignorance that it can ever end. 		-- Benjamin Disraeli ",
    "I have to think hard to name an interesting man who does not drink. 		-- Richard Burton ",
    "My family history begins with me, but yours ends with you. 		-- Iphicrates ",
    "The time for action is past!  Now is the time for senseless bickering. ",
    "It's possible that I'm just an idiot, and don't recognize a sleepy slavemaster when I see one. 		-- Larry Wall in <199708040319.UAA16213@wall.org> ",
    "Obey all traffic laws. ",
    "Accordion, n.: 	A bagpipe with pleats. ",
    "Not responsible for typographical errors. ",
    "A bug in the hand is better than one as yet undetected. ",
    "At the source of every error which is blamed on the computer you will find at least two human errors, including the error of blaming it on the computer. ",
    "Bershere's Formula for Failure: 	There are only two kinds of people who fail: those who 	listen to nobody... and those who listen to everybody. ",
    "Q:	How does a hacker fix a function which 	doesn't work for all of the elements in its domain? A:	He changes the domain. ",
    "The advertisement is the most truthful part of a newspaper. 		-- Thomas Jefferson ",
    "Edwin Meese made me wear CORDOVANS!! ",
    "hacker, n.: 	A master byter. ",
    "A girl's conscience doesn't really keep her from doing anything wrong-- it merely keeps her from enjoying it. ",
    "Sign here without admitting guilt. ",
    "I have to think hard to name an interesting man who does not drink. 		-- Richard Burton ",
    "The wise shepherd never trusts his flock to a smiling wolf. ",
    "Not SENSUOUS ... only \"FROLICSOME\" ... and in need of DENTAL WORK ... in PAIN!!! ",
    "The clash of ideas is the sound of freedom. ",
    "At many levels, Perl is a \"diagonal\" language. 		-- Larry Wall in <199709021854.LAA12794@wall.org> ",
    "I'm so broke I can't even pay attention. ",
    "The goal of Computer Science is to build something that will last at least until we've finished building it. ",
    "Many a writer seems to think he is never profound except when he can't understand his own meaning. 		-- George D. Prentice ",
    "God isn't dead, he just couldn't find a parking place. ",
    "Demand the establishment of the government in its rightful home at Disneyland. ",
    "Dignity is like a flag.  It flaps in a storm. 		-- Roy Mengot ",
    "He that teaches himself has a fool for a master. 		-- Benjamin Franklin ",
    "... If I had heart failure right now, I couldn't be a more fortunate man!! ",
    "National security is in your hands - guard it well. ",
    "\"I have a bone to pick, and a few to break.\" 		-- Anonymous ",
    "Fourth Law of Thermodynamics: 	If the probability of success is not almost one, it is damn near zero. 		-- David Ellis ",
    "Harris's Lament: 	All the good ones are taken. ",
    "The real reason psychology is hard is that psychologists are trying to do the impossible. ",
    "Abraham Lincoln didn't die in vain.  He died in Washington, D.C. ",
    "I have seen the Great Pretender and he is not what he seems. ",
    "There's nothing to writing.  All you do is sit at a typewriter and open a vein. 		-- Red Smith ",
    "Don't let your mind wander -- it's too little to be let out alone. ",
    "For some reason, this fortune reminds everyone of Marvin Zelkowitz. ",
    "Tact in audacity is knowing how far you can go without going too far. 		-- Jean Cocteau ",
    "Humor in the Court: Q.  And who is this person you are speaking of? A.  My ex-widow said it. ",
    "Bridge ahead.  Pay troll. ",
    "Old mail has arrived. ",
    "Declared guilty... of displaying feelings of an almost human nature. 		-- Pink Floyd, \"The Wall\" ",
    "The goal of science is to build better mousetraps.  The goal of nature is to build better mice. ",
    "To be trusted is a greater compliment than to be loved. ",
    "He was so narrow-minded he could see through a keyhole with both eyes. ",
    "\"Conversion, fastidious Goddess, loves blood better than brick, and feasts most subtly on the human will.\" 		-- Virginia Woolf, \"Mrs. Dalloway\" ",
    "Authors are easy to get on with -- if you're fond of children. 		-- Michael Joseph, \"Observer\" ",
    "\"Well, if you can't believe what you read in a comic book, what *can* you believe?!\" 		-- Bullwinkle J. Moose [Jay Ward] ",
    "Look DEEP into the OPENINGS!!  Do you see any ELVES or EDSELS ... or a HIGHBALL?? ... ",
    "Living on Earth may be expensive, but it includes an annual free trip around the Sun. ",
    "Well, I think Perl should run faster than C.  :-) 		-- Larry Wall in <199801200306.TAA11638@wall.org> ",
    "If condition persists, consult your physician. ",
    "A woman, especially if she have the misfortune of knowing anything, should conceal it as well as she can. 		-- Jane Austen ",
    "Running Windows on a Pentium is like having a brand new Porsche but only be able to drive backwards with the handbrake on.      -- Unknown source ",
    "Measure twice, cut once. ",
    "Arithmetic is being able to count up to twenty without taking off your shoes. 		-- Mickey Mouse ",
    "Fame lost its appeal for me when I went into a public restroom and an autograph seeker handed me a pen and paper under the stall door. 		-- Marlo Thomas ",
    "Avoid Quiet and Placid persons unless you are in Need of Sleep. 		-- National Lampoon, \"Deteriorata\" ",
    "YOU PICKED KARL MALDEN'S NOSE!! ",
    "Q:	What is the sound of one cat napping? A:	Mu. ",
    "We gave you an atomic bomb, what do you want, mermaids? 		-- I. I. Rabi to the Atomic Energy Commission ",
    "Do not use that foreign word \"ideals\".  We have that excellent native word \"lies\". 		-- Henrik Ibsen, \"The Wild Duck\" ",
    "If you can read this, you're too close. ",
    "I used to think that the brain was the most wonderful organ in my body.  Then I realized who was telling me this. 		-- Emo Phillips ",
    "We have nowhere else to go... this is all we have. 		-- Margaret Mead ",
    "Give all orders verbally.  Never write anything down that might go into a \"Pearl Harbor File\". ",
    "So live that you wouldn't be ashamed to sell the family parrot to the town gossip. ",
    "A woman without a man is like a fish without a bicycle. Therefore, a man without a woman is like a bicycle without a fish. ",
    "Man's reach must exceed his grasp, for why else the heavens? ",
    "The trouble with a kitten is that When it grows up, it's always a cat 		-- Ogden Nash. ",
    "	Inheritance taxes are getting so out of line, that the deceased family often doesn't have a legacy to stand on. ",
    "Specifications subject to change without notice. ",
    "Lots of people drink from the wrong bottle sometimes. 		-- Edith Keeler, \"The City on the Edge of Forever\", 		   stardate unknown ",
    "Q:	What's tan and black and looks great on a lawyer? A:	A doberman. ",
    "Don't know what time I'll be back, Mom.  Probably soon after she throws me out. ",
    "Just because your doctor has a name for your condition doesn't mean he knows what it is. ",
    "Respect is a rational process 		-- McCoy, \"The Galileo Seven\", stardate 2822.3 ",
    "You will be married within a year, and divorced within two. ",
    "You are a wish to be here wishing yourself. 		-- Philip Whalen ",
    "QOTD: 	\"I only touch base with reality on an as-needed basis!\" ",
    "Nice guys don't finish nice. ",
    "As long as the answer is right, who cares if the question is wrong? ",
    "\"A great many people think they are thinking when they are merely rearranging their prejudices.\" 		-- William James ",
    "\"The most important thing in a man is not what he knows, but what he is.\" 		-- Narciso Yepes ",
    "Beauty and harmony are as necessary to you as the very breath of life. ",
    "Perfect day for scrubbing the floor and other exciting things. ",
    "Ferengi Rule of Acquisition #6: Never allow family to stand in the way of opportunity. -- The Nagus (DS9 episode) ",
    "It's a poor workman who blames his tools. ",
    "If at first you do succeed, try to hide your astonishment. ",
    "God isn't dead, he just couldn't find a parking place. ",
    "I did it just to piss you off.  :-P 		-- Branden Robinson in a message to debian-devel ",
    "These screamingly hilarious gogs ensure owners of     X Ray Gogs to be the life of any party. 		-- X-Ray Gogs Instructions ",
    "<james> but, then I used an Atari, I was more likely to win the lottery in         ten countries simultaneously than get accelerated X ",
    "And tomorrow will be like today, only more so. 		-- Isaiah 56:12, New Standard Version ",
    "Have you seen the latest Japanese camera?  Apparently it is so fast it can photograph an American with his mouth shut! ",
    "Reply hazy, ask again later. ",
    "If you refuse to accept anything but the best you very often get it. ",
    "A watched clock never boils. ",
    "I don't make the rules, Gil, I only play the game. 		-- Cash McCall ",
    "Blutarsky's Axiom: 	Nothing is impossible for the man who will not listen to reason. ",
    "Computer Science is the only discipline in which we view adding a new wing to a building as being maintenance 		-- Jim Horning ",
    "<Stealth> How do I bind a computer to an NIS server? <Joey> Use a rope? 	-- Seen on #Debian ",
    "Love makes fools, marriage cuckolds, and patriotism malevolent imbeciles. 		-- Paul Leautaud, \"Passe-temps\" ",
    "The best things in life go on sale sooner or later. ",
    "People love high ideals, but they got to be about 33-percent plausible. 		-- The Best of Will Rogers ",
    "The solution to a problem changes the nature of the problem. 		-- Peer ",
    "s = (char*)(long)retval;                /* ouch */ 		-- Larry Wall in doio.c from the perl source code ",
    "\"Anyone attempting to generate random numbers by deterministic means is, of course, living in a state of sin.\" 		-- John Von Neumann ",
    "Wow, I'm being shot at from both sides.  That means I *must* be right.  :-) 		-- Larry Wall in <199710211959.MAA18990@wall.org> ",
    "Under every stone lurks a politician. 		-- Aristophanes ",
    "Ask not for whom the <CONTROL-G> tolls. ",
    "Why does a ship carry cargo and a truck carry shipments? ",
    "Woman inspires us to great things, and prevents us from achieving them. 		-- Dumas ",
    "I am a jelly donut.  I am a jelly donut. ",
    "An engineer is someone who does list processing in FORTRAN. ",
    "The end move in politics is always to pick up a gun. 		-- Buckminster Fuller ",
    "It were not best that we should all think alike; it is difference of opinion that makes horse-races. 		-- Mark Twain, \"Pudd'nhead Wilson's Calendar\" ",
    "You will give someone a piece of your mind, which you can ill afford. ",
    "Those who can, do; those who can't, write. Those who can't write work for the Bell Labs Record. ",
    "Quantum Mechanics is God's version of \"Trust me.\" ",
    "You will have good luck and overcome many hardships. ",
    "Arnold's Addendum: 	Anything not fitting into these categories causes cancer in rats. ",
    "Machine Always Crashes, If Not, The Operating System Hangs (MACINTOSH) 	-- Topic on #Linux ",
    "Beware of the Turing tar-pit in which everything is possible but nothing of interest is easy.     -- Alan Perlis ",
    "Humor in the Court: Q: (Showing man picture.) That's you? A: Yes, sir. Q: And you were present when the picture was taken, right? ",
    "Time sure flies when you don't know what you're doing. ",
    "Joe's sister puts spaghetti in her shoes! ",
    "I finally went to the eye doctor.  I got contacts.  I only need them to read, so I got flip-ups. 		-- Steven Wright ",
    "When you have an efficient government, you have a dictatorship. 		-- Harry Truman ",
    "\"And remember: Evil will always prevail, because Good is dumb.\" 		-- Spaceballs ",
    "If you laid all of our laws end to end, there would be no end. 		-- Mark Twain ",
    "economist, n: 	Someone who's good with figures, but doesn't have enough 	personality to become an accountant. ",
    "Approved for veterans. ",
    "Never, ever lie to someone you love unless you're absolutely sure they'll never find out the truth. ",
    "Don't smoke the next cigarette.  Repeat. ",
    "\"I'd love to go out with you, but the last time I went out, I never came back.\" ",
    "If you give Congress a chance to vote on both sides of an issue, it will always do it. 		-- Les Aspin, D., Wisconsin ",
    "Whatever is not nailed down is mine.  Whatever I can pry up is not nailed down. 		-- Collis P. Huntington, railroad tycoon ",
    "Don't get even -- get odd! ",
    "I'm proud to be paying taxes in the United States.  The only thing is -- I could be just as proud for half the money. 		-- Arthur Godfrey ",
    "Somewhere in Tenafly, New Jersey, a chiropractor is viewing \"Leave it to Beaver\"! ",
    "I'm a Lisp variable -- bind me! ",
    "Home on the Range was originally written in beef-flat. ",
    "I hate dying. 		-- Dave Johnson ",
    "<Flood> can I write a unix-like kernel in perl? ",
    "QOTD: 	\"Of course there's no reason for it, it's just our policy.\" ",
    "National security is in your hands - guard it well. ",
    "Planet Claire has pink hair. All the trees are red. No one ever dies there. No one has a head.... ",
    "Too much of everything is just enough. 		-- Bob Wier ",
    "No anchovies unless otherwise specified. ",
    "His heart was yours from the first moment that you met. ",
    "However, never daunted, I will cope with adversity in my traditional manner ... sulking and nausea. 		-- Tom K. Ryan ",
    "<Stealth> How do I bind a computer to an NIS server? <Joey> Use a rope? 	-- Seen on #Debian ",
    "Toto, I don't think we're in Kansas anymore. 		-- Judy Garland, \"Wizard of Oz\" ",
    "The Abrams' Principle: 	The shortest distance between two points is off the wall. ",
    "Remember: While root can do most everything, there are certain privileges that only a partner can grant. 	-- Telsa Gwynne ",
    "His ideas of first-aid stopped short of squirting soda water. 		-- P. G. Wodehouse ",
    "Old Mother Hubbard went to the cupboard To fetch her poor daughter a dress. When she got there, the cupboard was bare And so was her daughter, I guess... ",
    "As a computer, I find your faith in technology amusing. ",
    "No yak too dirty; no dumpster too hollow. ",
    "I understand why you're confused.  You're thinking too much. 		-- Carole Wallach. ",
    "Vegetarians beware!  You are what you eat. ",
    "I hold it, that a little rebellion, now and then, is a good thing... 		-- Thomas Jefferson ",
    "I want to dress you up as TALLULAH BANKHEAD and cover you with VASELINE and WHEAT THINS ... ",
    "It does not do to leave a live dragon out of your calculations. ",
    "Why on earth do people buy old bottles of wine when they can get a fresh one for a quarter of the price? ",
    "It's easier to get forgiveness for being wrong than forgiveness for being right. ",
    "You're always thinking you're gonna be the one that makes 'em act different. 		-- Woody Allen, \"Manhattan\" ",
    "<evilkalla> heh, I never took a coding class <evilkalla> or a graphics class <evilkalla> or a software design class <vegan> and it shows :P ",
    "blithwapping: 	Using anything BUT a hammer to hammer a nail into the 	wall, such as shoes, lamp bases, doorstops, etc. 		-- \"Sniglets\", Rich Hall & Friends ",
    "The only problem with being a man of leisure is that you can never stop and take a rest. ",
    "Support your right to arm bears!! ",
    "Computers will not be perfected until they can compute how much more than the estimate the job will cost. ",
    "This fortune soaks up 47 times its own weight in excess memory. ",
    "Corry's Law: 	Paper is always strongest at the perforations. ",
    "A yawn is a silent shout. 		-- G. K. Chesterton ",
    "\"Life is like a buffet; it's not good but there's plenty of it.\" ",
    "MY income is ALL disposable! ",
    "Yow!  I'm imagining a surfer van filled with soy sauce! ",
    "The meek don't want it. ",
    "<Knghtbrd> shaleh - unclean is just WEIRD. <Espy> heh, unclean is cool <Knghtbrd> Espy - and weird. <Espy> yes, weird too ",
    "If all the world's economists were laid end to end, we wouldn't reach a conclusion. 		-- William Baumol ",
    "I learned to play guitar just to get the girls, and anyone who says they didn't is just lyin'! 		-- Willie Nelson ",
    "Men of lofty genius when they are doing the least work are most active. 		-- Leonardo da Vinci ",
    "If it wasn't so warm out today, it would be cooler. ",
    "After an instrument has been assembled, extra components will be found on the bench. ",
    "Even moderation ought not to be practiced to excess. ",
    "Trespassers will be shot.  Survivors will be SHOT AGAIN! ",
    "Gomme's Laws: 	(1) A backscratcher will always find new itches. 	(2) Time accelerates. 	(3) The weather at home improves as soon as you go away. ",
    "I represent a sardine!! ",
    "Only the hypocrite is really rotten to the core. 		-- Hannah Arendt ",
    "Only great masters of style can succeed in being obtuse. 		-- Oscar Wilde  Most UNIX programmers are great masters of style. 		-- The Unnamed Usenetter ",
    "Ozmosis: 	The inability of one's job to live up to one's self-image. 		-- Douglas Coupland, \"Generation X: Tales for an Accelerated 		   Culture\" ",
    "This login session: $13.76, but for you $11.88. ",
    "One of the most overlooked advantages to computers is...  If they do foul up, there's no law against whacking them around a little. 		-- Joe Martin ",
    "I didn't get sophisticated -- I just got tired.  But maybe that's what sophisticated is -- being tired. 		-- Rita Gain ",
    "Facts are stubborn, but statistics are more pliable. ",
    "Ferengi Rule of Acquisition #45: Expand or die. -- Acquisition (ENT episode) ",
    "Absence makes the heart forget. ",
    "Sometimes, too long is too long. 		-- Joe Crowe ",
    "Thousands of days of civilians ... have produced a ... feeling for the aesthetic modules -- ",
    "42 ",
    "There are no accidents whatsoever in the universe. 		-- Baba Ram Dass ",
    "\"Hey Ivan, check your six.\" 		-- Sidewinder missile jacket patch, showing a Sidewinder driving up the tail  of a Russian Su-27 ",
    "A conclusion is simply the place where someone got tired of thinking. ",
    "He has not acquired a fortune; the fortune has acquired him. 		-- Bion ",
    "I'll say it again for the logic impaired. 		-- Larry Wall ",
    "Ninety percent of everything is crap. 		-- Theodore Sturgeon ",
    "\"How to make a million dollars:  First, get a million dollars.\" 		-- Steve Martin ",
    "Ferengi Rule of Acquisition #272: Always inspect the merchandise before making a deal. -- The Abandoned (DS9 episode), Star Trek Online (video game) ",
    "The two most common things in the Universe are hydrogen and stupidity. 		-- Harlan Ellison ",
    "Theorem: a cat has nine tails. Proof: 	No cat has eight tails. A cat has one tail more than no cat. 	Therefore, a cat has nine tails. ",
    "... Logically incoherent, semantically incomprehensible, and legally ... impeccable! ",
    "God doesn't play dice. 		-- Albert Einstein ",
    "What I need is a MATURE RELATIONSHIP with a FLOPPY DISK ... ",
    "Marriage is a romance in which the hero dies in the first chapter. ",
    "Nobody can be exactly like me.  Sometimes even I have trouble doing it. 		-- Tallulah Bankhead ",
    "You know it's going to be a long day when you get up, shave and shower, start to get dressed and your shoes are still warm. 		-- Dean Webber ",
    "Diplomacy is the art of letting the other party have things your way. 		-- Daniele Vare ",
    "It is far more impressive when others discover your good qualities without your help. 		-- Miss Manners ",
    "New crypt.  See /usr/news/crypt. ",
    "Usage: fortune -P [] -a [xsz] [Q: [file]] [rKe9] -v6[+] dataspec ... inputdir ",
    "All of the true things I am about to tell you are shameless lies. 		-- The Book of Bokonon / Kurt Vonnegut Jr. ",
    "A furore Normanorum libera nos, O Domine! 	[From the fury of the norsemen deliver us, O Lord!] 		-- Medieval prayer ",
    "\"If it ain't broke, don't fix it.\" 		-- Bert Lantz ",
    "Absolutely nothing should be concluded from these figures except that no conclusion can be drawn from them. 	-- Joseph L. Brothers, Linux/PowerPC Project) ",
    "A fail-safe circuit will destroy others. 		-- Klipstein ",
    "I think she must have been very strictly brought up, she's so desperately anxious to do the wrong thing correctly. 		-- Saki, \"Reginald on Worries\" ",
    "Do not write below this line. ",
    "Collaboration, n.: 	A literary partnership based on the false assumption that the 	other fellow can spell. ",
    "<elmo> Joy: thanks, joy <doogie> elmo: that's redundant, elmo <elmo> doogie: go play in traffic <doogie> ah, the elmo we know and love ",
    "Practical people would be more practical if they would take a little more time for dreaming. 		-- J. P. McEvoy ",
    "A snake lurks in the grass. 		-- Publius Vergilius Maro (Virgil) ",
    "To downgrade the human mind is bad theology. 		-- C. K. Chesterton ",
    "You have the power to influence all with whom you come in contact. ",
    "Teachers have class. ",
    "When a fly lands on the ceiling, does it do a half roll or a half loop? ",
    "Love is a grave mental disease. 		-- Plato ",
    "The average income of the modern teenager is about 2 a.m. ",
    "I hope you millionaires are having fun!  I just invested half your life savings in yeast!! ",
    "Shipping not included. ",
    "\"The chain which can be yanked is not the eternal chain.\" 		-- G. Fitch ",
    "Can anyone remember when the times were not hard, and money not scarce? ",
    "You've been telling me to relax all the way here, and now you're telling me just to be myself? 		-- The Return of the Secaucus Seven ",
    "Computers are not intelligent.  They only think they are. ",
    "Everyone wants results, but no one is willing to do what it takes to get them. 		-- Dirty Harry ",
    "Why be a man when you can be a success? 		-- Bertolt Brecht ",
    "No directory. ",
    "It is idle to attempt to talk a young woman out of her passion: love does not lie in the ear. 		-- Walpole ",
    "Nature abhors a virgin -- a frozen asset. 		-- Clare Booth Luce ",
    "I cannot conceive that anybody will require multiplications at the rate of 40,000 or even 4,000 per hour ... 		-- F. H. Wales (1936) ",
    "Ferengi Rule of Acquisition #1: Once you have their money, you never give it back. -- The Nagus (DS9 episode) ",
    "Be not anxious about what you have, but about what you are. 		-- Pope St. Gregory I ",
    "Boucher's Observation: 	He who blows his own horn always plays the music 	several octaves higher than originally written. ",
    "Not exactly as shown. ",
    "Work smarter, not harder, and be careful of your speling. ",
    "When asked by an anthropologist what the Indians called America before the white men came, an Indian said simply \"Ours.\" 		-- Vine Deloria, Jr. ",
    "If you want to make God laugh, tell him about your plans. 		-- Woody Allen ",
    "Binary, adj.: 	Possessing the ability to have friends of both sexes. ",
    "patent: 	A method of publicizing inventions so others can copy them. ",
    "He who walks on burning coals is sure to get burned. 		-- Sinbad ",
    "Drink Canada Dry!  You might not succeed, but it *is* fun trying. ",
    "\"The pathology is to want control, not that you ever get it, because of course you never do.\" 		-- Gregory Bateson ",
    "Never go to a doctor whose office plants have died. 		-- Erma Bombeck ",
    "She blinded me with science! ",
    "An intellectual is someone whose mind watches itself. 		-- Albert Camus ",
    "You know it's going to be a bad day when you want to put on the clothes you wore home from the party and there aren't any. ",
    "I'm also against BODY-SURFING!! ",
    "I think she must have been very strictly brought up, she's so desperately anxious to do the wrong thing correctly. 		-- Saki, \"Reginald on Worries\" ",
    "Go 'way!  You're bothering me! ",
    "I have to think hard to name an interesting man who does not drink. 		-- Richard Burton ",
    "An expert is one who knows more and more about less and less until he knows absolutely everything about nothing. ",
    "Are you selling NYLON OIL WELLS??  If so, we can use TWO DOZEN!! ",
    "This life is yours.  Some of it was given to you; the rest, you made yourself. ",
    "Truth has always been found to promote the best interests of mankind... 		-- Percy Bysshe Shelley ",
    "Yow!  Now I get to think about all the BAD THINGS I did to a BOWLING BALL when I was in JUNIOR HIGH SCHOOL! ",
    "Piece of cake! 		-- G. S. Koblas ",
    "If you wait long enough, it will go away... after having done its damage. If it was bad, it will be back. ",
    "You buttered your bread, now lie in it. ",
    "<kceee^> I hate users <knghtbrd> you sound like a sysadmin already! ",
    "The computer can't tell you the emotional story.  It can give you the exact mathematical design, but what's missing is the eyebrows. 		-- Frank Zappa ",
    "There is nothing new except what has been forgotten. 		-- Marie Antoinette ",
    "Anything that is worth doing has been done frequently.  Things hitherto undone should be given, I suspect, a wide berth. 		-- Max Beerbohm, \"Mainly on the Air\" ",
    "If there is no wind, row. 		-- Polish proverb ",
    "Charity begins at home. 		-- Publius Terentius Afer (Terence) ",
    "To err is human, but when the eraser wears out before the pencil, you're overdoing it a little. ",
    "Now hatred is by far the longest pleasure; Men love in haste, but they detest at leisure. 		-- George Gordon, Lord Byron, \"Don Juan\" ",
    "You'd better smile when they watch you, smile like you're in control. 		-- Smile, \"Was (Not Was)\" ",
    "Say no, then negotiate. 		-- Helga ",
    "In Tulsa, Oklahoma, it is against the law to open a soda bottle without the supervision of a licensed engineer. ",
    "It is only people of small moral stature who have to stand on their dignity. ",
    "In 1962, you could buy a pair of SHARKSKIN SLACKS, with a \"Continental Belt,\" for $10.99!! ",
    "You can tell the ideals of a nation by its advertisements. 		-- Norman Douglas ",
    "A full belly makes a dull brain. 		-- Ben Franklin  		[and the local candy machine man.  Ed] ",
    "One meets his destiny often on the road he takes to avoid it. ",
    "A new koan: 	If you have some ice cream, I will give it to you. 	If you have no ice cream, I will take it away from you. It is an ice cream koan. ",
    "Never trust a child farther than you can throw it. ",
    "New York's got the ways and means; Just won't let you be. 		-- The Grateful Dead ",
    "Don't interfere with the stranger's style. ",
    "If you live long enough, you'll see that every victory turns into a defeat. 		-- Simone de Beauvoir ",
    "Harriet's Dining Observation: 	In every restaurant, the hardness of the butter pats 	increases in direct proportion to the softness of the bread. ",
    "One would like to stroke and caress human beings, but one dares not do so, because they bite. 		-- Vladimir Il'ich Lenin ",
    "\"Humor is a drug which it's the fashion to abuse.\" 		-- William Gilbert ",
    "Behind every great man, there is a woman -- urging him on. 		-- Harry Mudd, \"I, Mudd\", stardate 4513.3 ",
    "They are relatively good but absolutely terrible. 		-- Alan Kay, commenting on Apollos ",
    "He's just a politician trying to save both his faces... ",
    "No transfers issued until the bus comes to a complete stop. ",
    "I would like to urinate in an OVULAR, porcelain pool -- ",
    "Perhaps the world's second worst crime is boredom.  The first is being a bore. 		-- Cecil Beaton ",
    "Never appeal to a man's \"better nature.\"  He may not have one. Invoking his self-interest gives you more leverage. 		-- Lazarus Long ",
    "Wedding rings are the world's smallest handcuffs. ",
    "\"Neighbors!!  We got neighbors!  We ain't supposed to have any neighbors, and I just had to shoot one.\" 		-- Post Bros. Comics ",
    "The proof of the pudding is in the eating. 		-- Miguel de Cervantes ",
    "The computing field is always in need of new cliches. 		-- Alan Perlis ",
    "\"Not only is God dead, but just try to find a plumber on weekends.\" --Woody Allen ",
    "System going down at 5 this afternoon to install scheduler bug. ",
    "Ever feel like life was a game and you had the wrong instruction book? ",
    "I've finally found the perfect girl, I couldn't ask for more, She's deaf and dumb and over-sexed, And owns a liquor store. ",
    "Creditor, n.: 	A man who has a better memory than a debtor. ",
    "I don't want to be young again, I just don't want to get any older. ",
    "If you love someone, set them free. If they don't come back, then call them up when you're drunk. ",
    "Federal grants are offered for... research into the recreation potential of interplanetary space travel for the culturally disadvantaged. ",
    "It's NO USE ... I've gone to \"CLUB MED\"!! ",
    "When a lion meets another with a louder roar, the first lion thinks the last a bore. 		-- G. B. Shaw ",
    "What excuses stand in your way?  How can you eliminate them? 		-- Roger von Oech ",
    "Everyone talks about apathy, but no one does anything about it. ",
    "Q:	Why haven't you graduated yet? A:	Well, Dad, I could have finished years ago, but I wanted 	my dissertation to rhyme. ",
    "\"Don't hate me because I'm beautiful.  Hate me because I'm beautiful, smart and rich.\" 		-- Calvin Keegan ",
    "All celebrity voices impersonated. ",
    "A CONS is an object which cares. 		-- Bernie Greenberg. ",
    "< Overfiend> whew. < Overfiend> I really need to get some sleep. < Overfiend> but it sure was fun talking guitars, politics, and lesbians. ",
    "It's not whether you win or lose, it's how you place the blame. ",
    "It is through symbols that man consciously or unconsciously lives, works and has his being. 		-- Thomas Carlyle ",
    "Tell me, O Octopus, I begs, Is those things arms, or is they legs? I marvel at thee, Octopus; If I were thou, I'd call me us. 		-- Ogden Nash ",
    "When a camel flies, no one laughs if it doesn't get very far! ",
    "You have a message from the operator. ",
    "Cleanliness becomes more important when godliness is unlikely. 		-- P. J. O'Rourke ",
    "I don't drink, I don't like it, it makes me feel too good. 		-- K. Coates ",
    "I'd like MY data-base JULIENNED and stir-fried! ",
    "Give me a sleeping pill and tell me your troubles. ",
    "Monotheism is a gift from the gods. ",
    "Were these parsnips CORRECTLY MARINATED in TACO SAUCE? ",
    "A bore is a man who talks so much about himself that you can't talk about yourself. ",
    "Perfection is reached, not when there is no longer anything to add, but when there is no longer anything to take away. 		-- Antoine de Saint-Exupery ",
    "Do not exceed recommended dosage. ",
    "If you are too busy to read, then you are too busy. ",
    "I prefer rogues to imbeciles because they sometimes take a rest. 		-- Alexandre Dumas, fils ",
    "The opulence of the front office door varies inversely with the fundamental solvency of the firm. ",
    "Girls who throw themselves at men, are actually taking very careful aim. ",
    "Advertising may be described as the science of arresting the human intelligence long enough to get money from it. ",
    "A bird in the hand is worth two in the bush. 		-- Cervantes ",
    "We'll try to cooperate fully with the IRS, because, as citizens, we feel a strong patriotic duty not to go to jail. 		-- Dave Barry ",
    "The SAME WAVE keeps coming in and COLLAPSING like a rayon MUU-MUU ... ",
    "History repeats itself only if one does not listen the first time. ",
    "Sailors in ships, sail on!  Even while we died, others rode out the storm. ",
    "...Unix, MS-DOS, and Windows NT (also known as the Good, the Bad, and the Ugly). 	-- Matt Welsh ",
    "This bag is recyclable. ",
    "Marriage is the only adventure open to the cowardly. 		-- Voltaire ",
    "Burnt Sienna.  That's the best thing that ever happened to Crayolas. 		-- Ken Weaver ",
    "You can't fall off the floor. ",
    "Ferengi Rule of Acquisition #8: Small print leads to large risk. -- The Ferengi Rules of Acquisition (DS9 reference book) ",
    "Humor in the Court: Q: Now, you have investigated other murders, have you not, where there was    a victim? ",
    "I found Rome a city of bricks and left it a city of marble. 		-- Augustus Caesar ",
    "Algebraic symbols are used when you do not know what you are talking about. 		-- Philippe Schnoebelen ",
    "falsie salesman, n: 	Fuller bust man. ",
    "People need good lies.  There are too many bad ones. 		-- Bokonon, \"Cat's Cradle\" by Kurt Vonnegut, Jr. ",
    "It usually takes more than three weeks to prepare a good impromptu speech. 		-- Mark Twain ",
    "My godda bless, never I see sucha people. 		-- Signor Piozzi, quoted by Cecilia Thrale ",
    "One can never consent to creep when one feels an impulse to soar. 		-- Helen Keller ",
    "Just because you're paranoid doesn't mean they AREN'T after you. ",
    "Flying is the second greatest feeling you can have.  The greatest feeling? Landing...  Landing is the greatest feeling you can have. ",
    "I've enjoyed just about as much of this as I can stand. ",
    "fortune: cpu time/usefulness ratio too high -- core dumped. ",
    "It is better to wear out than to rust out. ",
    "A modem is a baudy house. ",
    "Is it clean in other dimensions? ",
    "It is not well to be thought of as one who meekly submits to insolence and intimidation. ",
    "We prefer to speak evil of ourselves rather than not speak of ourselves at all. ",
    "\"First things first -- but not necessarily in that order\" 		-- The Doctor, \"Doctor Who\" ",
    "Talkers are no good doers. 		-- William Shakespeare, \"Henry VI\" ",
    "It's not whether you win or lose, it's how you place the blame. ",
    "You're almost as happy as you think you are. ",
    "A closed mouth gathers no foot. ",
    "Seen on a button at an SF Convention: Veteran of the Bermuda Triangle Expeditionary Force.  1990-1951. ",
    "QOTD: 	\"If I'm what I eat, I'm a chocolate chip cookie.\" ",
    "When you are in it up to your ears, keep your mouth shut. ",
    "Have a nice diurnal anomaly. ",
    "If your mother knew what you're doing, she'd probably hang her head and cry. ",
    "On the road, ZIPPY is a pinhead without a purpose, but never without a POINT. ",
    "Don't interfere with the stranger's style. ",
    "I like work; it fascinates me; I can sit and look at it for hours. ",
    "<SirDibos> Culus: are you awake? <Culus> no ",
    "There is no such thing as a problem without a gift for you in its hands. ",
    "Odd that we think definitions are definitive.   :-) 		-- Larry Wall in <199702221943.LAA20388@wall.org> ",
    "The Constitution may not be perfect, but it's a lot better than what we've got! ",
    "Whatever doesn't succeed in two months and a half in California will never succeed. 		-- Rev. Henry Durant, founder of the University of California ",
    "If I want your opinion, I'll ask you to fill out the necessary form. ",
    "\"I took the sweet life but I never knew I'd be bitter from the sweet\"      -- Charlene     -- I've Never Been to Me (  ) ",
    "It's better to be quotable than to be honest. 		-- Tom Stoppard ",
    "To teach is to learn twice. 		-- Joseph Joubert ",
    "Password: ",
    "\"There is such a fine line between genius and stupidity.\" 		-- David St. Hubbins, \"Spinal Tap\" ",
    "I have discovered that all human evil comes from this, man's being unable to sit still in a room. 		-- Blaise Pascal ",
    "Software is like sex; it's better when it's free. 	-- Linus Torvalds ",
    "\"I'd love to go out with you, but I have to stay home and see if I snore.\" ",
    "Life is not for everyone. ",
    "Overflow on /dev/null, please empty the bit bucket. ",
    "When the sun shineth, make hay. 		-- John Heywood ",
    "Facts are the enemy of truth. 		-- Don Quixote ",
    "Crime does not pay ... as well as politics. 		-- Alfred E. Newman ",
    "A long-forgotten loved one will appear soon.  Buy the negatives at any price. ",
    "A fool-proof method for sculpting an elephant: first, get a huge block of marble; then you chip away everything that doesn't look like an elephant. ",
    "One man's \"magic\" is another man's engineering.  \"Supernatural\" is a null word. 		-- Robert Heinlein ",
    "What fools these morals be! ",
    "Be valiant, but not too venturous. Let thy attire be comely, but not costly. 		-- John Lyly ",
    "\"Lead us in a few words of silent prayer.\" 		-- Bill Peterson, former Houston Oiler football coach ",
    "Deceive Inveigle Obfuscate     -- The X-Files, Season 4, Episode 3, \"Teliko\" ",
    "Know Thy User. ",
    "lisp, v.: 	To call a spade a thpade. ",
    "Truth never comes into the world but like a bastard, to the ignominy of him that brought her birth. 		-- Milton ",
    "Love the sea?  I dote upon it -- from the beach. ",
    "This novel is not to be tossed lightly aside, but to be hurled with great force. 		-- Dorothy Parker ",
    "You will think of something funnier than this to add to the fortunes. ",
    "<Mercury> Knghtbrd: Hey, perl has the power grace and elegance of a sledge           hammer. (=:] <|Rain|> certainly the grace and elegance, anyway ",
    "Lay on, MacDuff, and curs'd be him who first cries, \"Hold, enough!\". 		-- Shakespeare ",
    "30 day money back guarantee minus shipping, 10% restocking charge, and 7% cancellation charge. ",
    "After years of research, scientists recently reported that there is, indeed, arroz in Spanish Harlem. ",
    "April 1  This is the day upon which we are reminded of what we are on the other three hundred and sixty-four. 		-- Mark Twain, \"Pudd'nhead Wilson's Calendar\" ",
    "Work continues in this area. 		-- DEC's SPR-Answering-Automaton ",
    "Q:	How many Marxists does it take to screw in a light bulb? A:	None:  The light bulb contains the seeds of its own revolution. ",
    "The [Ford Foundation] is a large body of money completely surrounded by people who want some. 		-- Dwight MacDonald ",
    "Your compliance with all terms and conditions, expressed and implied, is automatic upon viewing. ",
    "A businessman is a hybrid of a dancer and a calculator. 		-- Paul Valery ",
    "In defeat, unbeatable; in victory, unbearable. 		-- W. Churchill, on General Montgomery ",
    "The cool thing about Vim is — you find something interesting with every typo.      -- Su-Shee     -- Freenode’s #perl conversation ",
    "Laugh at your problems; everybody else does. ",
    "No, I'm not going to explain it.  If you can't figure it out, you didn't want to know anyway...  :-) 		-- Larry Wall in <1991Aug7.180856.2854@netlabs.com> ",
];
function getRandomFortune() { return fortunes[Math.floor(Math.random() * fortunes.length)]; }
